/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-05-14 02:10:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.expense.outpatient.fee;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class opExpDaybalanceList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525761782870L));
    _jspx_dependants.put("/commons/include/html_doctype.html", Long.valueOf(1525761798654L));
    _jspx_dependants.put("/commons/include/get.jsp", Long.valueOf(1525827802831L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>门诊收费日结</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/boot.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/commons/dynamic.jsp\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/template/jquery.tmpl.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/default/css/web.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/print.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t//初始化\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\t// 初始化查询时间\r\n");
      out.write("\t\tyearMonth.setValue(new Date()); \r\n");
      out.write("\t\t//本次日结时间初始化\r\n");
      out.write("\t\tnowTime.setValue(new Date());\r\n");
      out.write("\t\t//打印时间\r\n");
      out.write("\t\t$(\"#printTime\").text(mini.formatDate(new Date(),\"yyyy-MM-dd HH:mm:ss\")); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//获取最后一次日结时间\r\n");
      out.write("\t\tgetLastTime();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//获取树菜单\r\n");
      out.write("\t\tgetTree();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//加载主报表、明细报表\r\n");
      out.write("\t\tgetDayReport(\"-1\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 刷新页面\r\n");
      out.write("\tfunction refresh() {\r\n");
      out.write("\t\twindow.location.reload();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 显示上次日结时间\r\n");
      out.write("\tfunction getLastTime() {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/fee/opExpDaybalance/getLastTime.do\";\r\n");
      out.write("\t\t$.ajaxSetup({async : false});\r\n");
      out.write("\t\t$.post(url,{validFlag:'1',daybalanceType:'2'},function (r) {\r\n");
      out.write("\t\t\tif(r != null) {\r\n");
      out.write("\t\t\t\tr = $.decode(r);\r\n");
      out.write("\t\t\t\tif (r.success) {\r\n");
      out.write("\t\t\t\t\tdaybalanceEndTime.setValue(r.tag);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ttop.mini.alert(r.message);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 获取预交金日结树\r\n");
      out.write("\tfunction getTree() {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/fee/opExpDaybalance/getTree.do?yearMonth=\"+ mini.formatDate(yearMonth.getValue(),\"yyyy-MM-dd\")+\"&daybalanceType=2\";\r\n");
      out.write("\t\ttree.load(url);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 查询并加载 主报表/明细报表 数据\r\n");
      out.write("\tfunction getDayReport(e) {\r\n");
      out.write("\t\tvar node = e.node;\r\n");
      out.write("\t\tvar daybalanceId = \"-1\";\r\n");
      out.write("\t\tif (node) {\r\n");
      out.write("\t\t\tif (node.id==\"root\") {\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdaybalanceId = node.id;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar beginTime = mini.formatDate(daybalanceEndTime.getValue(),\"yyyy-MM-dd HH:mm:ss\");\r\n");
      out.write("\t\tvar endTime = mini.formatDate(nowTime.getValue(),\"yyyy-MM-dd HH:mm:ss\");\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpReceipt/getReport.do\";\r\n");
      out.write("\t\t$.ajaxSetup({async : false});\r\n");
      out.write("\t\t$.post(url,{daybalanceId:daybalanceId,beginTime:beginTime,endTime:endTime},function(r) {\r\n");
      out.write("\t\t\tform1.clear();\r\n");
      out.write("\t\t\t$(\".reportList\").remove();\r\n");
      out.write("\t\t\t// 主报表\r\n");
      out.write("\t\t\tvar str =\"\";\r\n");
      out.write("\t\t\tfor(var i=0;i<r.feeTypeCosts.length;i++) {\r\n");
      out.write("\t\t\t\tstr += '<tr class=\"reportList\">' +\r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ r.feeTypeCosts[i].id1 + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ r.feeTypeCosts[i].name1 + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ ((r.feeTypeCosts[i].id2 == undefined) ? \"\" : r.feeTypeCosts[i].id2) + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ ((r.feeTypeCosts[i].name2 == undefined) ? \"\" : r.feeTypeCosts[i].name2) + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ ((r.feeTypeCosts[i].id3 == undefined) ? \"\" : r.feeTypeCosts[i].id3) + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ ((r.feeTypeCosts[i].name3 == undefined) ? \"\" : r.feeTypeCosts[i].name3) + '</td>' + \r\n");
      out.write("\t\t\t\t\t'</tr>';\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#content\").after(str);\r\n");
      out.write("\t\t\tform1.setData(r);\r\n");
      out.write("\t\t\tmini.get(\"sumCost\").setValue(mini.get(\"caCost\").getValue());// 计算费用合计\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 明细报表\r\n");
      out.write("\t\t\tvar str2 =\"\";\r\n");
      out.write("\t\t\tvar cost = 0.00;\r\n");
      out.write("\t\t\tfor(var i=0;i<r.reportList.length;i++) {\r\n");
      out.write("\t\t\t\tstr2 = '<tr class=\"reportList\">' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ r.reportList[i].serialNo + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ r.reportList[i].receiptNo + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ r.reportList[i].patientName + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ r.reportList[i].paymentCost + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\">'+ r.reportList[i].paymentName + '</td>' + \r\n");
      out.write("\t\t\t\t\t\t'<td align=\"center\"></td>';\r\n");
      out.write("\t\t\t\tif(!r.reportList[i].des) {\r\n");
      out.write("\t\t\t\t\tstr2 = str2 + '<td align=\"center\"></td>';\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tstr2 = str2 + '<td align=\"center\">'+ r.reportList[i].des + '</td></tr>';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcost = cost + r.reportList[i].paymentCost;\r\n");
      out.write("\t\t\t\t$(\"#content2\").after(str2);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmini.get(\"cost\").setValue(cost.toFixed(2));\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 日结确认\r\n");
      out.write("\tfunction save() {\r\n");
      out.write("\t\tmini.confirm(\"确认日结？\",\"提示\",\r\n");
      out.write("\t\t\tfunction (action) {\r\n");
      out.write("\t\t\t\tif (action == \"ok\") {\r\n");
      out.write("\t\t\t\t\tdayBalance();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 执行日结\r\n");
      out.write("\tfunction dayBalance() {\r\n");
      out.write("\t\tvar dtBeginTime = mini.get(\"daybalanceEndTime\").getValue();\r\n");
      out.write("\t\tvar dtEndTime = mini.get(\"nowTime\").getValue();\r\n");
      out.write("\t\tvar data = {\r\n");
      out.write("\t\t\tdtBeginTime : mini.formatDate(dtBeginTime,\"yyyy-MM-dd HH:mm:ss\"),\r\n");
      out.write("\t\t\tdtEndTime : mini.formatDate(dtEndTime,\"yyyy-MM-dd HH:mm:ss\"),\r\n");
      out.write("\t\t\tdaybalanceType : \"2\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/fee/opExpDaybalance/save.do\";\r\n");
      out.write("\t\t$.post(url,data,function (r) {\r\n");
      out.write("\t\t\t if (r) {\r\n");
      out.write("\t\t\t\tmini.alert(r);\r\n");
      out.write("\t\t\t\tgetTree();\r\n");
      out.write("\t\t\t\tgetLastTime();\r\n");
      out.write("\t\t\t\tmini.get(\"daybalanceEndTime\").setValue(new Date());\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\ttop.mini.error(r);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//打印\r\n");
      out.write("\tfunction onPrint() {\r\n");
      out.write("\t\tPrint(\"#main\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//明细打印\r\n");
      out.write("\tfunction printList() {\r\n");
      out.write("\t\tPrint(\"#list\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 显示\r\n");
      out.write("\tfunction show() {\r\n");
      out.write("\t\t$(\".hideBegin\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"mini-toolbar hideBegin\" style=\"display:none;\" borderStyle=\"border-top:0;border-right:0;border-left:0;border-bottom:1;\">\r\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-refresh\" onclick=\"refresh\">刷新</a>\r\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-window-print\" onclick=\"onPrint\">打印</a>\r\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-window-print\" onclick=\"printList\">明细打印</a>\r\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-save\" onclick=\"save\">日结</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mini-fit\">\r\n");
      out.write("\t    <div class=\"mini-splitter hideBegin\" style=\"display:none;width:100%;height:100%;\" borderStyle=\"border-top:0;margin-top:3px;\">\r\n");
      out.write("\t\t\t<div size=\"15%;\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t<div class=\"mini-toolbar\" borderStyle=\"border-top:0;border-right:0;border-left:0;border-bottom:1;\">\r\n");
      out.write("\t\t    \t\t<span style=\"font-size:14px;\">月份：</span>\r\n");
      out.write("\t\t\t\t\t<input id=\"yearMonth\" class=\"mini-datepicker\" onvaluechanged=\"getTree()\" format=\"yyyy-MM\"  style=\"width:100px;\"/>\r\n");
      out.write("\t\t\t\t\t<a class=\"mini-button\" iconCls=\"icon-search\" onclick=\"getTree\">查询</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t\t\t\t<ul id=\"tree1\" resultAsTree=\"false\" class=\"mini-tree\" expandOnLoad=\"true\"\r\n");
      out.write("\t\t\t    \t\tshowArrow=\"true\" showTreeIcon=\"true\"  showCheckBox=\"false\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width:100%;height:100%;\" onnodedblclick=\"getDayReport\" >\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t    <div size=\"85%;\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t    \t<div class=\"mini-toolbar\" borderStyle=\"border-top:0;border-right:0;border-left:0;border-bottom:1;\">\r\n");
      out.write("\t\t    \t\t<span style=\"font-size:14px;\">上次日结时间：</span>\r\n");
      out.write("\t\t\t\t\t<input id=\"daybalanceEndTime\" class=\"mini-datepicker\" format=\"yyyy-MM-dd HH:mm:ss\" enabled=\"false\" style=\"width:170px;\"/>&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t    \t\t<span style=\"font-size:14px;\">本次日结时间：</span>\r\n");
      out.write("\t\t\t\t\t<input id=\"nowTime\" class=\"mini-datepicker\" format=\"yyyy-MM-dd HH:mm:ss\"  style=\"width:170px;\"/>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t\t       \t<div class=\"mini-tabs\" style=\"width:100%;height:100%;\" showCollapseButton=\"false\" activeIndex=\"0\" borderStyle=\"border:0;\">\r\n");
      out.write("\t\t\t       \t\t<div title=\"主报表\">\r\n");
      out.write("\t\t\t       \t\t\t<div id =\"form1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"main\" width=\"700\" border=\"1\"\r\n");
      out.write("\t\t\t       \t\t\t\t\tstyle=\"border:solid 1px #000000;border-collapse:collapse;margin:1em;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th colspan=\"6\" align=\"center\"><h3>收费员日报表</h3></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\" align=\"center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr id=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">项目</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">金额</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">项目</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">金额</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">项目</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">金额</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">现金</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"caCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"caCost\" name=\"caCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">支票</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"chCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"chCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">银联卡</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"upCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"upCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">转账</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"zzCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"zzCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">医保卡</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"mcCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"mcCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">结欠</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"jqCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"jqCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">预收款</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"yskCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"yskCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">托管</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"tgCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"tgCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">实收小计</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"totCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"totCost\" name=\"totCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">公医记账</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"mcpCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"mcpCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">医保记账</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"gyCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"gyCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">铁路IC卡</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"qtybCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"qtybCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">铁路医保记账</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"tlybCostUpper\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"tlybCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">医院分担</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"xxx\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"xxx\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">铁路医保误差</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"xxx\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"xxx\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">费用合计</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\" align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input id=\"sumCost\" name=\"sumCost\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name = \"operName\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\">收款员：　　　（金额手写及未盖章无效）</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">退号收据编号</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"5\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"cancels\" class=\"mini-textarea\" borderStyle=\"border:0;\" readOnly=\"true\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">作废收据编号</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"5\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"invalids\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align=\"center\">收据号码</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"5\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"invoiceNos\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"operTime\" class=\"mini-textbox\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t       \t\t</div>\r\n");
      out.write("\t\t\t       \t\t<div title=\"明细报表\">\r\n");
      out.write("\t\t       \t\t\t\t<table id=\"list\" width=\"700\" border=\"1\"\r\n");
      out.write("\t\t       \t\t\t\t\tstyle=\"border:solid 1px #000000;border-collapse:collapse;margin:1em;\">\r\n");
      out.write("\t\t       \t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th colspan=\"7\" align=\"center\"><h3>收费员日报表明细</h3></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"7\" align=\"center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${baseInfo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr id=\"content2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">收据号</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">收据编号</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">病人姓名</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">金额</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">支付方式</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">票号</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">备注</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">合计：</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input id=\"cost\" class=\"mini-textbox\" inputStyle=\"text-align:center;\" borderStyle=\"border:0;\" readOnly=\"true\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td align=\"center\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td colspan=\"7\" align=\"left\"> &nbsp;打印时间：<span id=\"printTime\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t       \t\t\t\t</table>\r\n");
      out.write("\t\t\t       \t\t</div>\r\n");
      out.write("\t\t\t       \t</div>\r\n");
      out.write("\t\t       \t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tmini.parse();\r\n");
      out.write("\t\tvar yearMonth = mini.get(\"yearMonth\");\r\n");
      out.write("\t\tvar nowTime = mini.get(\"nowTime\");\r\n");
      out.write("\t\tvar daybalanceEndTime = mini.get(\"daybalanceEndTime\");\r\n");
      out.write("\t\tvar tree = mini.get(\"tree1\");\r\n");
      out.write("\t\tvar form1 = new mini.Form(\"#main\");\r\n");
      out.write("\t\tinit();\r\n");
      out.write("\t\tshow();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /commons/include/get.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /commons/include/get.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/get.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /commons/include/get.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("emr");
      // /commons/include/get.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/get.jsp(6,0) '${emrContextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${emrContextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
