/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-05-14 07:57:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.expense.outpatient;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class outRecConfirmSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525761782870L));
    _jspx_dependants.put("/commons/include/html_doctype.html", Long.valueOf(1525761798654L));
    _jspx_dependants.put("/commons/include/form.jsp", Long.valueOf(1525761798651L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>终端确认_门诊已确认查询</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<!-- <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" /> -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/default/css/web.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/boot.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/commons/dynamic.jsp\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/misc/jquery.form.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/core.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\ttr {\r\n");
      out.write("\t\theight:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.blue {\r\n");
      out.write("\t\tfont-weight:bold;\r\n");
      out.write("\t\tfont-size:13px; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.patientInfo {\r\n");
      out.write("\t\t color:blue;  \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.mini-buttonedit-icon {\r\n");
      out.write("\t\tdisplay:none;\r\n");
      out.write("\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t.mini-splitter .mini-splitter-pane2 {\r\n");
      out.write("    \tborder: 0;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\t// 当前点击的患者\r\n");
      out.write("\tvar currentPatient = null;\r\n");
      out.write("\tvar currentApplyId = null;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 刷新\r\n");
      out.write("\tfunction refresh() {\r\n");
      out.write("\t\tvar startDate = mini.formatDate(confirmTime.getValue(), \"yyyy-MM-dd\");\r\n");
      out.write("\t\tvar endDate = mini.parseDate(startDate);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/getConfirmRegister.do\";\r\n");
      out.write("\t\tvar data = {\r\n");
      out.write("\t\t\tstartDate : startDate,\r\n");
      out.write("\t\t\tendDate : endDate\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t$.post(url, data, function(r) {\r\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\r\n");
      out.write("\t\t\t\ttree.loadList(r.tree);\r\n");
      out.write("\t\t\t\tgrid.clearRows();\r\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\r\n");
      out.write("\t\t\t\ttop.mini.alert(r.message);\r\n");
      out.write("\t\t\t} else if(parseInt(r.state == 0)) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* $.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/getConfirmRegister.do\",\r\n");
      out.write("\t\t\tdata: {patientId : e.row.patientId},\r\n");
      out.write("\t\t\tasync: false ,\r\n");
      out.write("\t\t\tsuccess: function(r) {\r\n");
      out.write("\t\t\t\tif(r.resultList.length <= 0) {\r\n");
      out.write("\t\t\t\t\ttop.mini.alert(\"没有找到\" + e.row.patientName + \"的门诊待确认信息\");\r\n");
      out.write("\t\t\t\t} else { \r\n");
      out.write("\t\t\t\t\tvar node = tree.getSelectedNode();\r\n");
      out.write("\t\t\t\t\tform.setData(node); \r\n");
      out.write("\t\t\t\t\tgrid.load({\r\n");
      out.write("\t\t\t\t\t\tregisterId : r.resultList[1].id\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\twin.hide();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}); */\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 点击某个患者的时候\r\n");
      out.write("\tfunction onnodeclick(e) { \r\n");
      out.write("\t\tif(e.row.pid) {\r\n");
      out.write("\t\t\tqueryData(e.row.id);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 点击挂号列表\r\n");
      out.write("\tfunction onrowdblclick(e) {\r\n");
      out.write("\t\tqueryData(e.row.registerId);\r\n");
      out.write("\t\twin.hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 通过registerId获取页面数据\r\n");
      out.write("\tfunction queryData(registerId) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/findRegister.do\";\r\n");
      out.write("\t\tvar fn = \r\n");
      out.write("\t\t$.post(url, {registerId: registerId}, function(r) {\r\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\r\n");
      out.write("\t\t\t\tsetData(r);\r\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\r\n");
      out.write("\t\t\t\tmini.showTips({content: r.message, state: \"warning\", x: \"center\", y: \"center\", timeout: 3000});\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 根据唯一号查询患者\r\n");
      out.write("\tfunction onenter(e) {\r\n");
      out.write("\t\tvar patientId = e.sender.value;\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/getByPatientId.do\";\r\n");
      out.write("\t\tvar fn = function(r) {\r\n");
      out.write("\t\t\tif(r.length > 1) {\r\n");
      out.write("\t\t\t\tgrid3.loadData(r);\r\n");
      out.write("\t\t\t\twin.setTitle(\"挂号列表\");\r\n");
      out.write("\t\t\t\twin.show();\r\n");
      out.write("\t\t\t} else if(r.length == 1) {\r\n");
      out.write("\t\t\t\tqueryData(r[0].registerId);\r\n");
      out.write("\t\t\t} else if(r.length == 0) {\r\n");
      out.write("\t\t\t\tmini.showTips({content: \"没有找到对应的患者\",\r\n");
      out.write("\t\t\t\t\t\t\tstate: \"warning\",\r\n");
      out.write("\t\t\t\t\t\t\tx: \"center\",\r\n");
      out.write("\t\t\t\t\t\t\ty: \"center\",\r\n");
      out.write("\t\t\t\t\t\t\ttimeout: 3000});\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.post(url,{patientId : patientId}, fn);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 页面设值\r\n");
      out.write("\tfunction setData(data) {\r\n");
      out.write("\t\tform.setData(data.register);\r\n");
      out.write("\t\tgrid.loadData(data.data);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 渲染\r\n");
      out.write("\tfunction ondrawcell(e) {\r\n");
      out.write("\t/* \tif (apply.Charge.Flag)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvalue = \"已计费\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvalue = \"未计费\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tstring value2 = string.Empty;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (apply.Confirm.Flag)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvalue2 = \"已确认\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvalue2 = \"未确认\";\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\tif (e.column.field == \"confirmFlag\") {\r\n");
      out.write("\t\t\tif (e.value == \"1\") {\r\n");
      out.write("\t\t\t\te.cellHtml = \"<span>已确认</span>\";\r\n");
      out.write("\t\t\t} else if (e.value == \"0\") {\r\n");
      out.write("\t\t\t\te.cellHtml =\"<span>未确认</span>\";\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(e.column.field == \"balanceFlag\") { \r\n");
      out.write("\t\t\tif (e.value == \"1\") {\r\n");
      out.write("\t\t\t\te.cellHtml = \"<span>已计费</span>\";\r\n");
      out.write("\t\t\t} else if (e.value == \"0\") {\r\n");
      out.write("\t\t\t\te.cellHtml =\"<span>未计费</span>\";\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 全选\r\n");
      out.write("\tfunction selectAll() { \r\n");
      out.write("\t\tgrid.selectAll();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 全不选\r\n");
      out.write("\tfunction deselectAll () {\r\n");
      out.write("\t\tgrid.deselectAll();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 点击某行\r\n");
      out.write("\t/* function onrowclick(e) {  // aaa\r\n");
      out.write("\t\tvar subItems = e.row.tag.subList;\r\n");
      out.write("\t\tvar detail = \"\";\r\n");
      out.write("\t\tfor(var i = 0; i < subItems.length; i++) {\r\n");
      out.write("\t\t\tif(parseInt(subItems[i].dataSource) != 2) {\r\n");
      out.write("\t\t\t\tdetail += (i+1) + \".\" + subItems[i].itemName + \" 价格:\" + subItems[i].price + \" 数量:\" + subItems[i].qty + \"\" + \"<br/>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#detailInfo\").html(\"明细信息: <br/>\" + detail);\r\n");
      out.write("\t\t$(\"#applyInfo\").html(e.row.itemName);\r\n");
      out.write("\t\tvar terminalApplys = [];\r\n");
      out.write("\t\tfor(var i = 0; i < subItems.length; i++) {\r\n");
      out.write("\t\t\tif(parseInt(subItems[i].dataSource) == 2) {\r\n");
      out.write("\t\t\t\tterminalApplys.push(subItems[i]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\tgrid1.loadData(terminalApplys);\r\n");
      out.write("\t} */\r\n");
      out.write("\t\r\n");
      out.write("\t// \r\n");
      out.write("\tfunction onrowclick(e) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/setDetailInfo.do\";\r\n");
      out.write("\t\tvar data = {\r\n");
      out.write("\t\t\tnondrugId: e.row.itemId,\r\n");
      out.write("\t\t\tapplyId: e.row.applyId\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.post(url, data, function(r) {\r\n");
      out.write("\t\t\t$(\"#detailInfo\").html(r.replace(\"null\", \"\"));\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t// 加载附加项目\r\n");
      out.write("\t\t$(\"#applyInfo\").html(e.row.itemName);\r\n");
      out.write("\t\tvar subItems = e.row.tag.subList;\r\n");
      out.write("\t\tvar detail = \"\";\r\n");
      out.write("\t\tfor(var i = 0; i < subItems.length; i++) {\r\n");
      out.write("\t\t\tif(parseInt(subItems[i].dataSource) != 2) {\r\n");
      out.write("\t\t\t\tdetail += (i+1) + \".\" + subItems[i].itemName + \" 价格:\" + subItems[i].price + \" 数量:\" + subItems[i].qty + \"；</br>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar terminalApplys = [];\r\n");
      out.write("\t\tfor(var i = 0; i < subItems.length; i++) {\r\n");
      out.write("\t\t\tif(parseInt(subItems[i].dataSource) == 2) {\r\n");
      out.write("\t\t\t\tterminalApplys.push(subItems[i]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\tgrid1.loadData(terminalApplys);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 增加一行\r\n");
      out.write("\tfunction add() { \r\n");
      out.write("\t\tvar rowIndex = 0;\r\n");
      out.write("\t\tvar outOrder = grid.getSelected();\r\n");
      out.write("\t\tif(!outOrder)return;\r\n");
      out.write("\t\tvar newRow = {\r\n");
      out.write("\t\t\tregisterId : currentPatient.id, \r\n");
      out.write("\t\t\tapplyId : outOrder.applyId, \r\n");
      out.write("\t\t\tregisterDeptId : currentPatient.registerDeptId, \r\n");
      out.write("\t\t\trecipeDoctId : outOrder.recipeDoctId, \r\n");
      out.write("\t\t\trecipeDeptId : outOrder.recipeDeptId, \r\n");
      out.write("\t\t\tstockDeptId : outOrder.stockDeptId,\r\n");
      out.write("\t\t\torderId : outOrder.orderId,\r\n");
      out.write("\t\t\torderBillId : outOrder.billId,\r\n");
      out.write("\t\t\torderGroupNo : outOrder.groupNo,\r\n");
      out.write("\t\t\torderCombId : outOrder.combId,\r\n");
      out.write("\t\t\torderSortNo : outOrder.sortNo,\r\n");
      out.write("\t\t\torderOnceDosage : outOrder.onceDosage,\r\n");
      out.write("\t\t\torderOnceDosageUnit : outOrder.onceDosageUnit,\r\n");
      out.write("\t\t\torderFrequency : outOrder.frequency,\r\n");
      out.write("\t\t\torderUsageId : outOrder.usageId,\r\n");
      out.write("\t\t\torderUsageName : outOrder.usageName,\r\n");
      out.write("\t\t\torderEmergencyFlag : outOrder.emergencyFlag,\r\n");
      out.write("\t\t\torderSubjobFlag : outOrder.subjobFlag,\r\n");
      out.write("\t\t\torderSpecimen : outOrder.specimen,\r\n");
      out.write("\t\t\tapplyState : '0',\r\n");
      out.write("\t\t\tbalanceTime : new Date(0),\r\n");
      out.write("\t\t\tdataSourceWay : '1',\r\n");
      out.write("\t\t\torderCheckPoint : \"0\",\r\n");
      out.write("\t\t\tneedConfirmFlag : \"0\",\r\n");
      out.write("\t\t\torderExecuteTime : new Date()\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tgrid1.addRow(newRow, 0);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 删除划价\r\n");
      out.write("\tfunction del(e) {  \r\n");
      out.write("\t\tvar rows = grid1.getSelecteds();\r\n");
      out.write("\t\tif (rows.length <= 0) {\r\n");
      out.write("\t\t\ttop.mini.alert(\"没有数据！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/delConfirmAdd.do\";\r\n");
      out.write("\t\tvar fn = function(r) {\r\n");
      out.write("\t\t\tif (r == \"ok\") {\r\n");
      out.write("\t\t\t\ttop.mini.alert(\"成功！\");\r\n");
      out.write("\t\t\t\tgrid1.load({\r\n");
      out.write("\t\t\t\t\tapplyId : currentApplyId\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\ttop.mini.error(r, \"提示\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.post(url, {data : mini.encode(rows)}, fn);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 保存\r\n");
      out.write("\tfunction save(e) { \r\n");
      out.write("\t\tvar rows = grid1.getChanges();\r\n");
      out.write("\t\tif(rows.length <= 0) {\r\n");
      out.write("\t\t\ttop.mini.alert(\"没有数据！\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/confirmSave.do\";\r\n");
      out.write("\t\tvar fn = function(r) {\r\n");
      out.write("\t\t\tif(r == \"ok\") {\r\n");
      out.write("\t\t\t\ttop.mini.alert(\"保存成功！\");\r\n");
      out.write("\t\t\t\tgrid1.load({\r\n");
      out.write("\t\t\t\t\tapplyId : currentApplyId\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\ttop.mini.error(r, \"提示\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.post(url, {data : mini.encode(rows)}, fn);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 手动添加\r\n");
      out.write("\tfunction onValueChanged1(e) {\r\n");
      out.write("\t\tif(!e.selected)return;\r\n");
      out.write("\t\tfillOrder(e.selecteds[0].itemId);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 医嘱信息回填( 手动 )\r\n");
      out.write("\tfunction fillOrder(itemId) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/outOrder/fillOrder.do\";\r\n");
      out.write("\t\tvar fn = function(r) {\r\n");
      out.write("\t\t\tif(r.tip == \"NO\") {\r\n");
      out.write("\t\t\t\ttop.mini.alert(r.message);\r\n");
      out.write("\t\t\t} else if(r.tip == \"YES\") {\r\n");
      out.write("\t\t\t\tif(r.orderMap.itemSysType == \"HR\") {\r\n");
      out.write("\t\t\t\t\ttop.mini.alert(\"不允许在此界面开立草药医嘱！请点击【草药】按钮开立草药!\");\r\n");
      out.write("\t\t\t\t\tgrid1.updateRow(grid1.getSelected(), {itemSysType : \"\"});\r\n");
      out.write("\t\t\t\t\treturn ;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tr.orderMap.executeDeptId = r.orderMap.execDeptId;\r\n");
      out.write("\t\t\t\tr.orderMap.price = r.orderMap.itemPrice;\r\n");
      out.write("\t\t\t\tgrid1.updateRow(grid1.getSelected(), r.orderMap);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t$.post(url, {itemId : itemId}, fn);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 初始化日期\r\n");
      out.write("\tfunction setDate() {\r\n");
      out.write("\t\tvar date = mini.formatDate(new Date(), \"yyyy-MM-dd\");\r\n");
      out.write("\t\tconfirmTime.setValue(date);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 取消确认\r\n");
      out.write("\tfunction cancelConfirm(e) {\r\n");
      out.write("\t\tvar list = grid.getSelecteds();\r\n");
      out.write("\t\tif(list.length <= 0) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/cancelConfirm.do\";\r\n");
      out.write("\t\tvar data = {\r\n");
      out.write("\t\t\t\tdata : mini.encode(list)\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar fn = function(r) {\r\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\r\n");
      out.write("\t\t\t\ttop.mini.alert(\"取消确认成功！\");\r\n");
      out.write("\t\t\t\trefresh();\r\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\r\n");
      out.write("\t\t\t\ttop.mini.error(r.message);\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\ttop.mini.error(r);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t$.post(url, data, fn);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 显示\r\n");
      out.write("\tfunction show() {\r\n");
      out.write("\t\t$(\".hideBegin\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttop.on(\"EVENT_ORG_CHANGED\", refresh);\r\n");
      out.write("\t$(window).unload(function() {\r\n");
      out.write("\t\ttop.un(\"EVENT_ORG_CHANGED\", refresh);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t<div class=\"mini-splitter\" style=\"width:100%;height:100%;\" allowResize=\"true\" handlerSize=\"6\" borderStyle=\"border-top:0;\">\r\n");
      out.write("\t\t    <div size=\"300px\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t    \t<div class=\"header hideBegin\" style=\"display:none; padding: 3px 0 3px 10px;\">\r\n");
      out.write("\t\t    \t\t 日期  <input class=\"mini-datepicker\" id=\"confirmTime\" onvaluechanged=\"refresh\"/>\r\n");
      out.write("\t\t    \t\t<a class=\"mini-button\"  borderStyle=\"border:0;\" iconCls=\"fa fa-refresh\" onclick=\"refresh\"> 刷新</a>\r\n");
      out.write("\t\t    \t\t<!-- <input class=\"mini-checkbox\"/> 科室患者 -->\r\n");
      out.write("\t\t    \t</div>\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t    \t<div class=\"mini-fit\">\r\n");
      out.write("\t\t\t    \t<ul id=\"tree1\" class=\"mini-tree\" resultAsTree=\"false\" onnodeclick=\"onnodeclick\" expandOnLoad=\"true\"\r\n");
      out.write("\t\t\t    \t\tstyle=\"width:100%;height:100%;margin:0;padding:2px;\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t    <div showCollapseButton=\"false\">\r\n");
      out.write("\t\t    \t<div class=\"mini-splitter hideBegin\" style=\"display:none; width:100%;height:100%;\" allowResize=\"true\" handlerSize=\"6\">\r\n");
      out.write("\t\t\t\t    <div showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t    \t<div class=\"mini-splitter\" vertical=\"true\" style=\"width:100%;height:100%;\" allowResize=\"false\" handlerSize=\"6\">\r\n");
      out.write("\t\t\t\t\t\t    <div showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t\t\t    \t<div id=\"form1\">\r\n");
      out.write("\t\t\t\t\t\t\t    \t<div style=\"height:40px;line-height:40px;\">\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t<a class=\"mini-button\" borderStyle=\"border:0;\" onclick=\"selectAll\" iconCls=\"fa fa-plus-circle\">全选</a>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t<a class=\"mini-button\" borderStyle=\"border:0;\" onclick=\"deselectAll\" iconCls=\"fa fa-minus-circle\">全不选</a>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t<a class=\"mini-button\" borderStyle=\"border:0;\" onclick=\"cancelConfirm\" iconCls=\"fa fa-times-circle\">取消确认</a>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t <span style=\"color:blue;\"> &nbsp;&nbsp;唯一号&nbsp;</span><input class=\"mini-textbox\" name=\"patientId\" onenter=\"onenter\"/>\r\n");
      out.write("\t\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t    \t<hr/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<table style=\"width:900px; margin:0 0 0 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"patientInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t患者姓名：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"mini-textbox\" name=\"patientName\" style=\"width:80px\" borderStyle=\"border:0\" readOnly=\"true\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"patientInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t性　　别：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"mini-combobox\" name=\"sexCode\" style=\"width:80px\" borderStyle=\"border:0;\" readOnly=\"true\" data=\"[{id:1,text:'男'},{id:2,text:'女'}]\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"patientInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t挂号日期：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"mini-datePicker\" style=\"width:120px\" name=\"registerTime\" borderStyle=\"border:0\" readOnly=\"true\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"patientInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t挂号科室：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"mini-combobox\" style=\"width:150px\"  name=\"registerDeptId\" borderStyle=\"border:0\" readOnly=\"true\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"patientInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t医保类型：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"mini-combobox\" style=\"width:80px\" name=\"patientMedicalTypeId\" style=\"width:80px\" borderStyle=\"border:0\"  readOnly=\"true\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/common/medicalType/getKVs.do\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"patientInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t年　　龄：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"mini-textbox\" style=\"width:80px\" name=\"age\" borderStyle=\"border:0;\" readOnly=\"true\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td class=\"patientInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t看诊日期：\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td  colspan=\"3\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"mini-datePicker\" style=\"width:120px\" name=\"seeTime\" borderStyle=\"border:0\" readOnly=\"true\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mini-splitter\"  vertical=\"false\" style=\"width:100%;height:100%;\" allowResize=\"false\" handlerSize=\"-1\" borderStyle=\"border-top:0;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<div size=\"60%\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"mini-datagrid\" id=\"grid1\" showPager=\"false\" borderStyle=\"border:0;border-right:1px solid #ccc;\" onrowclick=\"onrowclick\" ondrawcell=\"ondrawcell\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/getConfirmOrder.do\" style=\"width:100%;height:100%;\" multiSelect=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div field=\"itemId\" headerAlign=\"center\" align=\"center\">项目编码</div> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div type=\"checkColumn\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"applyId\" headerAlign=\"center\" width=\"150\" align=\"center\">项目编码</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"itemName\" headerAlign=\"center\" width=\"300\" align=\"center\">项目名称</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"totCost\"  headerAlign=\"center\" align=\"center\">单价</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"qty\" headerAlign=\"center\" align=\"center\">项目数量</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"qtyUnit\" headerAlign=\"center\" align=\"center\">单位</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"totCost\" headerAlign=\"center\" align=\"center\">项目总金额</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"confirmFlag\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">项目状态</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"balanceFlag\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">是否收费</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"operId\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">执行人\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<div showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t<div id=\"detailInfo\" style=\"font-size:5px;padding:10px; border-top:1px solid #ccc; color:blue;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t\t信息\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t    <div size=\"200px;\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t\t\t    \t<div class=\"header\" style=\"color:blue;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t申请信息 : <span id=\"applyInfo\"></span>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t    \t\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"grid2\" class=\"mini-datagrid\" borderStyle=\"border:0;border-top:1px solid #ccc;\" style=\"width: 100%; height: 100%;\" allowSortColumn=\"true\" allowCellSelect=\"true\" ondrawcell=\"ondrawcell\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/getConfirmAdd.do\"\tshowPager=\"false\" multiSelect=\"true\" allowCellValid=\"true\" allowCellEdit=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t   <div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div type=\"indexColumn\" width=\"50\" headerAlign=\"center\" align=\"center\">序号</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"itemId\" name=\"taskName\" displayField=\"itemName\" width=\"340\"  headerAlign=\"center\" align=\"center\" vtype=\"required\"> 项目名称\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div property=\"editor\" class=\"mini-autocomplete\" valueFromSelect=\"true\" style=\"width:100%;\" required=\"true\" onvaluechanged=\"onValueChanged1\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t allowInput=\"true\" popupWidth=\"800\" valueField=\"itemId\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pharmacy/common/comDrug/getDrugList.do?notSysType=HR\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div property=\"columns\">\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div header=\"编号\" field=\"itemId\" headerAlign=\"center\" align=\"center\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div header=\"名称\" field=\"itemName\" width=\"200px\" headerAlign=\"center\" align=\"center\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div header=\"单价\" field=\"itemPrice\" headerAlign=\"center\" align=\"center\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div header=\"系统分类\" field=\"itemSysType\" type=\"comboboxcolumn\" headerAlign=\"center\" align=\"center\" visible=\"true\">系统分类\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=ITEM_SYS_TYPE\" readOnly=\"true\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div header=\"编号\" field=\"itemNo\" headerAlign=\"center\" align=\"center\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div header=\"规格\" field=\"specs\" headerAlign=\"center\" align=\"center\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div header=\"单位\" field=\"ordDosageUnit\" headerAlign=\"center\" align=\"center\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"specs\"  headerAlign=\"center\" align=\"center\">规格</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"price\" headerAlign=\"center\" align=\"center\">单价</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"showUnit\" headerAlign=\"center\" align=\"center\">单位</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"qty\" headerAlign=\"center\" align=\"center\">数量</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"totCost\" headerAlign=\"center\" align=\"center\">金额</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"balanceFlag\" headerAlign=\"center\" align=\"center\">是否收费\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"balanceTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\">收费时间</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"dataSourceWay\"  type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">记账方式\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" data=\"[{id:0,text:'手工记账'},{id:1,text:'医嘱记账'},{id:2,text:'后台记账'}]\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"executeDeptId\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">执行科室\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div field=\"confirmFlag\" headerAlign=\"center\" align=\"center\">项目状态\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <div size=\"0px;\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 通过唯一号查询到多个患者的时候 -->\r\n");
      out.write("\t<div id=\"win1\" class=\"mini-window\" style=\"width:50%;\">\r\n");
      out.write("\t\t<div class=\"mini-fit\">\r\n");
      out.write("\t         <div id=\"grid4\" class=\"mini-datagrid\" showPager=\"false\" borderStyle=\"border-right:0px solid #ccc;border-bottom:0px solid #ccc;border-left:1px solid #ccc;\" allowCellSelect=\"true\" \r\n");
      out.write("\t\t\t\t style=\"width:100%; height:100%;\" showTreeIcon=\"true\" treeColumn=\"taskname\" onrowdblclick=\"onrowdblclick\"\r\n");
      out.write("\t\t\t\t resultAsTree=\"false\" multiSelect=\"true\" allowCellValid=\"true\" allowCellEdit=\"true\">\r\n");
      out.write("\t\t\t\t <div property=\"columns\">\r\n");
      out.write("\t\t\t\t \t<div type=\"indexColumn\">序号</div>\r\n");
      out.write("\t\t\t        <div field=\"registerId\" width=\"150\" headerAlign=\"center\" align=\"center\">挂号流水号</div>\r\n");
      out.write("\t\t\t        <div field=\"patientName\" width=\"150\" headerAlign=\"center\" align=\"center\">姓名</div>\r\n");
      out.write("\t\t\t        <div field=\"age\" width=\"150\" headerAlign=\"center\" align=\"center\">年龄</div>\r\n");
      out.write("\t\t\t        <div field=\"registerTime\" width=\"150\" headerAlign=\"center\" align=\"center\">挂号日期</div>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tmini.parse();\r\n");
      out.write("\t\tshow();\r\n");
      out.write("\t\tvar grid = mini.get(\"grid1\");\r\n");
      out.write("\t\tvar grid1 = mini.get(\"grid2\");\r\n");
      out.write("\t\tvar grid2 = mini.get(\"grid3\");\r\n");
      out.write("\t\tvar grid3 = mini.get(\"grid4\");\r\n");
      out.write("\t\tvar tree = mini.get(\"tree1\");\r\n");
      out.write("\t\tvar win = mini.get(\"win1\");\r\n");
      out.write("\t\tvar tree1 = mini.get(\"tree2\");\r\n");
      out.write("\t\tvar confirmTime = mini.get(\"#confirmTime\");\r\n");
      out.write("\t\tvar form = new mini.Form(\"#form1\");\r\n");
      out.write("\t\tsetDate();\r\n");
      out.write("\t\trefresh();\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /commons/include/form.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /commons/include/form.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/form.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /commons/include/form.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("ctx_rpt");
      // /commons/include/form.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/form.jsp(6,0) '${reportContextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${reportContextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
