/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-05-15 02:01:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.platform.console;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.2.RELEASE.jar", Long.valueOf(1525761782942L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/spring-security-taglibs-4.2.2.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1488410132000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525761782870L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>医院信息系统-简版</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n");
      out.write("<meta name=\"renderer\" content=\"webkit\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/favicon.ico\" rel=\"icon\" type=\"image/x-icon\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/favicon.ico\" rel=\"shortcut icon\" type=\"image/x-icon\" />\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/menu/sidemenu.css\" rel=\"stylesheet\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/boot.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/core.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/menu/sidemenu.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 微软雅黑,宋体,Arial,Helvetica,Verdana,sans-serif;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topbar {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 80px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    width: 80px;\r\n");
      out.write("    /*background: #2c3849;*/\r\n");
      out.write("    background: #1a889a;\r\n");
      out.write("    overflow: visible;\r\n");
      out.write("    z-index: 2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    left: 80px;\r\n");
      out.write("    top: 40px;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    background: #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-header{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:60px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tmargin-top:10px;\r\n");
      out.write("}\r\n");
      out.write(".logo {\r\n");
      out.write("    padding-left: 15px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    line-height: 40px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #2c3849;\r\n");
      out.write("    font-weight:bolder;\r\n");
      out.write("}\r\n");
      out.write(".exit{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("    margin-top: -23px;\r\n");
      out.write("    margin-right: 15px;\r\n");
      out.write("    font-size:20px;\r\n");
      out.write("    color:black;\r\n");
      out.write("}\r\n");
      out.write("#footer .mini-textbox {\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("}\r\n");
      out.write("#footer .mini-textbox-input {\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tcolor:blue;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    if(top != this) {\r\n");
      out.write("\t\ttop.location = '");
      out.print(request.getContextPath());
      out.write("/platform/console/main.do';\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    var user_cache_key = \"user.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysUser.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    \r\n");
      out.write("    // 响应超时处理\r\n");
      out.write("    var timeoutLock = false;\r\n");
      out.write("    function handleTimeout(who) {\r\n");
      out.write("    \tif (timeoutLock) {\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tvar that = window;\r\n");
      out.write("    \ttimeoutLock = true;\r\n");
      out.write("    \tvar data = {\r\n");
      out.write("    \t\troleId : roleCombo.getValue(),\r\n");
      out.write("    \t\torgId : orgCombo.getValue(),\r\n");
      out.write("    \t\taccount : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysUser.account}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("    \t\tuserId : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysUser.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("    \t\tusername : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysUser.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tmini.open({\r\n");
      out.write("    \t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/timeout.jsp\",\r\n");
      out.write("          \ttitle: \"重新登录\", width: 500, height: 330,\r\n");
      out.write("          \tonload: function () {\r\n");
      out.write("            \tvar iframe = this.getIFrameEl();\r\n");
      out.write("              \tiframe.contentWindow.setData(data);\r\n");
      out.write("          \t},\r\n");
      out.write("          \tondestroy: function (action) {\r\n");
      out.write("          \t\tthat.timeoutLock = false;\r\n");
      out.write("          \t\tif (action == \"ok\") {\r\n");
      out.write("          \t\t\ttry {\r\n");
      out.write("          \t\t\t\tif (who) {\r\n");
      out.write("          \t\t\t\t\twho.location.reload();\t\r\n");
      out.write("          \t\t\t\t}\r\n");
      out.write("          \t\t\t} catch (e) {\r\n");
      out.write("          \t\t\t}\r\n");
      out.write("          \t\t}\r\n");
      out.write("          \t}\r\n");
      out.write("      \t});\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("\tfunction onBeforeOpen(e) {\r\n");
      out.write("\t\tcurrentTab = tabs.getTabByEvent(e.htmlEvent);\r\n");
      out.write("\t\tif (!currentTab) {\r\n");
      out.write("\t\t\te.cancel = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeTab() {\r\n");
      out.write("\t\tif (!currentTab) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (currentTab.name == 'home') {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttabs.removeTab(currentTab);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeAllBut() {\r\n");
      out.write("\t\tvar but = [ currentTab ];\r\n");
      out.write("\t\tbut.push(tabs.getTab(\"home\"));\r\n");
      out.write("\t\ttabs.removeAll(but);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeAll() {\r\n");
      out.write("\t\tvar but = [];\r\n");
      out.write("\t\tbut.push(tabs.getTab(\"home\"));\r\n");
      out.write("\t\ttabs.removeAll(but);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 当前角色发生变化\r\n");
      out.write("\tfunction onRoleChanged(e) {\r\n");
      out.write("\t\tvar roleId = roleCombo.getValue();\r\n");
      out.write("\t\t// 加载科室列表\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getByRoleAndEmployeeId.do?roleId=\"+roleId;\r\n");
      out.write("\t\torgCombo.setUrl(url);\r\n");
      out.write("\t\tvar cache = LS.get(user_cache_key);\r\n");
      out.write("\t\tif (orgCombo.findItems(cache[\"orgId\"]).length == 0) {\r\n");
      out.write("\t\t\torgCombo.select(0);\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\torgCombo.setValue(cache[\"orgId\"]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tonOrgChanged();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 加载主菜单\r\n");
      out.write("\t\tgetMenu(roleId);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcache[\"roleId\"] = roleId;\r\n");
      out.write("\t\tcache[\"orgId\"] = orgCombo.getValue();\r\n");
      out.write("\t\tLS.set(user_cache_key, cache);\r\n");
      out.write("\t\troleText.innerText = roleCombo.getText();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 加载主菜单\r\n");
      out.write("\tfunction getMenu (roleId) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/console/getMenuTree.do\";\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            url: url,\r\n");
      out.write("            data: {roleId:roleId},\r\n");
      out.write("            dataType: \"json\",\r\n");
      out.write("            async:false,\r\n");
      out.write("            success: function(menuData){\r\n");
      out.write("            \tif (menuData) {\r\n");
      out.write("    \t\t\t\t$(\"#menu1\").sidemenu({\r\n");
      out.write("    \t\t\t\t    data: menuData,\r\n");
      out.write("    \t\t\t    });\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("            }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 当前科室发生变化\r\n");
      out.write("\tfunction onOrgChanged(e) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/console/switchCurrentOrg.do\";\r\n");
      out.write("\t\t$.post(url, {orgId: orgCombo.getValue()}, function (r) {\r\n");
      out.write("\t\t\t$(window).trigger(\"EVENT_ORG_CHANGED\");\r\n");
      out.write("\t\t\tvar cache = LS.get(user_cache_key);\r\n");
      out.write("\t\t\tcache[\"orgId\"] = orgCombo.getValue();\r\n");
      out.write("\t\t\tLS.set(user_cache_key, cache);\r\n");
      out.write("\t\t\torgText.innerText = orgCombo.getText();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction on(event, fn) {\r\n");
      out.write("\t\t$(window).bind(event, fn);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction un(event, fn) {\r\n");
      out.write("\t\t$(window).unbind(event, fn);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction closeTab(e) {\r\n");
      out.write("\t\tif (e.tab.name == 'home') {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\te.sender.removeTab(e.tab);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 打开切换角色和科室窗口\r\n");
      out.write("\tfunction openWindow(v) {\r\n");
      out.write("\t\tif (v == \"role\") {\r\n");
      out.write("\t\t\troleWin.show();\r\n");
      out.write("\t\t} else if (v == \"org\") {\r\n");
      out.write("\t\t\torgWin.show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 打开修改个人信息页面\r\n");
      out.write("\tfunction personalInfo() {\r\n");
      out.write("\t\tvar node = {\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/get.do\",\r\n");
      out.write("\t\t\tid : \"01\",\r\n");
      out.write("\t\t\tresName : \"修改个人信息\",\r\n");
      out.write("\t\t\tfirstChild : {className : \"fa fa-pencil-square-o\"}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tshowTab(node);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 修改密码\r\n");
      out.write("\tfunction changePassword() {\r\n");
      out.write("\t\tvar node = {\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/modifyPwdView.do\",\r\n");
      out.write("\t\t\tid : \"02\",\r\n");
      out.write("\t\t\tresName : \"修改登录密码\",\r\n");
      out.write("\t\t\tfirstChild : {className : \"fa fa-pencil\"}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tshowTab(node);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    function showTab(node) {\r\n");
      out.write("        var tabs = mini.get(\"tabs1\");\r\n");
      out.write("        var id = \"tab$\" + node.id;\r\n");
      out.write("        var tab = tabs.getTab(id);\r\n");
      out.write("\r\n");
      out.write("        var iconCls;\r\n");
      out.write("        if(node.firstChild) {\r\n");
      out.write("        \ticonCls=node.firstChild.className;\r\n");
      out.write("        } else {\r\n");
      out.write("        \ticonCls=\"\";\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        var title;\r\n");
      out.write("        if(!node.innerText) {\r\n");
      out.write("        \ttitle = node.resName;\r\n");
      out.write("        } else {\r\n");
      out.write("        \ttitle = node.innerText;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (!tab) {\r\n");
      out.write("            tab = {};\r\n");
      out.write("            tab.name = id;\r\n");
      out.write("            tab.title = title;\r\n");
      out.write("            tab.showCloseButton = true;\r\n");
      out.write("            tab.url = node.url;\r\n");
      out.write("            if (iconCls) {\r\n");
      out.write("            \ttab.iconCls=iconCls;\r\n");
      out.write("            }\r\n");
      out.write("            tabs.addTab(tab);\r\n");
      out.write("        }\r\n");
      out.write("        tabs.activeTab(tab);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"topbar\">\r\n");
      out.write("        <a class=\"logo\" href=\"#\">\r\n");
      out.write("           \t 超树HIS系统\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"exit\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\"><span class=\"sidemenu-icon fa fa fa-power-off\"></span></a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("    \t<div class=\"user-header\">\r\n");
      out.write("    \t\t<a href=\"javascript:personalInfo();\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/login/images/user-header.png\" width=\"60\"></img></a>\r\n");
      out.write("    \t</div>\r\n");
      out.write("        <div id=\"menu1\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div id=\"tabs1\" class=\"mini-tabs\" ontabdblclick=\"closeTab\" activeIndex=\"0\" style=\"height:96%;\">\r\n");
      out.write("            <div title=\"首页\" name=\"home\" iconCls=\"fa fa-desktop\" url=\"\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"footer\" class=\"mini-toolbar\" style=\"height:4%;width:100%;\">\r\n");
      out.write("        \t<label style=\"margin-left:10px;\">当前科室：</label>\r\n");
      out.write("\t    \t<a id=\"orgText\" style=\"color:#f53e05;font-size:10pt;\" href=\"javascript:;\" onclick=\"openWindow('org')\" ></a>\r\n");
      out.write("\t    \t<span class=\"separator\"></span>\r\n");
      out.write("\t    \t<label>当前角色：</label>\r\n");
      out.write("\t    \t<a id=\"roleText\" style=\"color:#f53e05;font-size:10pt;\" href=\"javascript:;\" onclick=\"openWindow('role')\"></a>\r\n");
      out.write("\t    \t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t<a id=\"sysuser\" style=\"color:blue;font-size:10pt;\" href=\"javascript:;\" onclick=\"personalInfo();\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysUser.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sysUser.account}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t\t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t<a hidefocus=\"true\" style=\"font-size:10pt;-webkit-user-select:none;\" href=\"javascript:;\" onclick=\"changePassword();\">修改密码</a>\r\n");
      out.write("\t\t\t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t<span style=\"color:#1f2529;-webkit-user-select:none;\" hidefocus=\"true\">系统消息:&nbsp;</span>\r\n");
      out.write("\t\t\t<span style=\"color:#1f2529\" id=\"messageWebSocket\"></span>\r\n");
      out.write("\t\t\t<span class=\"separator\"></span>\r\n");
      out.write("\t\t\t<span style=\"color:#1f2529;-webkit-user-select:none;font-weight:500;color:blue;\" hidefocus=\"true\">IP:&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${IP}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- window1 -->\r\n");
      out.write("    <div id=\"win1\" class=\"mini-window\" title=\"选择角色\" height=\"200px\">\r\n");
      out.write("    \t<input id=\"roleCombo\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysRole/getByUserId.do\"\r\n");
      out.write("    \t\tvalueField=\"roleId\" textField=\"roleName\" allowInput=\"true\"\r\n");
      out.write("\t\t\tborderStyle=\"border-left:0px;border-right:0px;border-top:0px;\" \r\n");
      out.write("   \t\t\tstyle=\"width:100%\" onvaluechanged=\"onRoleChanged\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- window2 -->\r\n");
      out.write("    <div id=\"win2\" class=\"mini-window\" title=\"选择科室\" height=\"200px\">\r\n");
      out.write("    \t<input id=\"orgCombo\" class=\"mini-combobox\" borderStyle=\"border-top:0;border-left:0;\" allowInput=\"true\"\r\n");
      out.write("\t\t\tvalueField=\"orgId\" textField=\"orgName\" onvaluechanged=\"onOrgChanged\" popupMaxHeight=\"530\" \r\n");
      out.write("\t\t\tstyle=\"width:100%\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tmini.parse();\r\n");
      out.write("\t\tvar orgCombo = mini.get(\"orgCombo\");\r\n");
      out.write("\t\tvar roleCombo = mini.get(\"roleCombo\");\r\n");
      out.write("\t\tvar roleWin = mini.get(\"win1\");\r\n");
      out.write("\t\tvar orgWin = mini.get(\"win2\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar cache = LS.get(user_cache_key);\r\n");
      out.write("\t\tif (roleCombo.findItems(cache[\"roleId\"]).length == 0) {\r\n");
      out.write("\t\t\troleCombo.select(0);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\troleCombo.setValue(cache[\"roleId\"]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tonRoleChanged();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\torgText.innerText = orgCombo.getText();\r\n");
      out.write("\t\t\troleText.innerText = roleCombo.getText();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/view/platform/console/main.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/view/platform/console/main.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/platform/console/main.jsp(8,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
