/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-05-14 01:42:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.medical.operation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class outOpsApplyUpdateView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525761782870L));
    _jspx_dependants.put("/commons/include/html_doctype.html", Long.valueOf(1525761798654L));
    _jspx_dependants.put("/commons/include/get.jsp", Long.valueOf(1525827802831L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/boot.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/commons/dynamic.jsp\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/template/jquery.tmpl.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/default/css/web.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>门诊医生-手术申请</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t#fd1,#fd2,#fd3,#fd4{\r\n");
      out.write("\t\twidth:96%;border:#ccc 1px solid;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.submintButton{\r\n");
      out.write("\t\twidth:90%;\r\n");
      out.write("\t\tmargin:auto;\r\n");
      out.write("\t\tmargin-top:10px;\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.submintButton .msg{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tcolor:red;\r\n");
      out.write("\t}\r\n");
      out.write("\t.shuName{\r\n");
      out.write("\t\twidth:90px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main{color:#4f81bd;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t// 初始化\r\n");
      out.write("\tfunction query() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/operation/outOpsApply/getByApplyId.do\",\r\n");
      out.write("\t\t\tdata: {applyId: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.applyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"},\r\n");
      out.write("\t\t\tasync: false ,\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tvar form = new mini.Form(\"form1\");\r\n");
      out.write("\t\t\t\tform.setData(data);\r\n");
      out.write("\t\t\t\tdiagNameadmitDiagnose = mini.get(\"combo1\");\r\n");
      out.write("\t\t\t\tdiagNameadmitDiagnose1 = mini.get(\"combo2\");\r\n");
      out.write("\t\t\t\tdiagNameadmitDiagnose2 = mini.get(\"combo3\");\r\n");
      out.write("\t\t\t\titemNameadmitDiagnose = mini.get(\"combo4\");\r\n");
      out.write("\t\t\t\titemNameadmitDiagnose1 = mini.get(\"combo5\");\r\n");
      out.write("\t\t\t\titemNameadmitDiagnose2 = mini.get(\"combo6\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tdiagNameadmitDiagnose.setText(data.diagName);\r\n");
      out.write("\t\t\t\tdiagNameadmitDiagnose1.setText(data.diagName2);\r\n");
      out.write("\t\t\t\tdiagNameadmitDiagnose2.setText(data.diagName3);\r\n");
      out.write("\t\t\t\titemNameadmitDiagnose.setText(data.itemName);\r\n");
      out.write("\t\t\t\titemNameadmitDiagnose1.setText(data.itemName2);\r\n");
      out.write("\t\t\t\titemNameadmitDiagnose2.setText(data.itemName3);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 诊断1的值改变的事件\r\n");
      out.write("\tfunction onDiagnoseValuechanged1(e){\r\n");
      out.write("\t\tvar dgname1 = mini.get(\"diagName1\");\r\n");
      out.write("\t\tvar comb1 = mini.get(\"combo1\");\r\n");
      out.write("\t\tdgname1.setValue(comb1.text);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 诊断2的值改变的事件\r\n");
      out.write("\tfunction onDiagnoseValuechanged2(e){\r\n");
      out.write("\t\tvar dgname2 = mini.get(\"diagName2\");\r\n");
      out.write("\t\tvar comb2 = mini.get(\"combo2\");\r\n");
      out.write("\t\tdgname2.setValue(comb2.text);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 诊断3的值改变的事件\r\n");
      out.write("\tfunction onDiagnoseValuechanged3(e){\r\n");
      out.write("\t\tvar dgname3 = mini.get(\"diagName3\");\r\n");
      out.write("\t\tvar comb3 = mini.get(\"combo3\");\r\n");
      out.write("\t\tdgname3.setValue(comb3.text);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//  拟手术名称1的值改变的事件\r\n");
      out.write("\tfunction onOperationValuechanged1(e){\r\n");
      out.write("\t\tvar itemName1 = mini.get(\"itemName1\");\r\n");
      out.write("\t\tvar comb4 = mini.get(\"combo4\");\r\n");
      out.write("\t\titemName1.setValue(comb4.text);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 拟手术名称2的值改变的事件\r\n");
      out.write("\tfunction onOperationValuechanged2(e){\r\n");
      out.write("\t\tvar itemName2 = mini.get(\"itemName2\");\r\n");
      out.write("\t\tvar comb5 = mini.get(\"combo5\");\r\n");
      out.write("\t\titemName2.setValue(comb5.text);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 由手术者确定术者科室\r\n");
      out.write("\tfunction changeDept(e) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getByAccount.do\",\r\n");
      out.write("\t\t\tdata: {account: e.value},\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tsuccess: function (r){\r\n");
      out.write("\t\t\t\tif(r) {\r\n");
      out.write("\t\t\t\t\tmini.get(\"combo15\").setValue(r.orgId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//拟手术名称3的值改变的事件\r\n");
      out.write("\tfunction onOperationValuechanged3(e){\r\n");
      out.write("\t\tvar itemName3 = mini.get(\"itemName3\");\r\n");
      out.write("\t\tvar comb6 = mini.get(\"combo6\");\r\n");
      out.write("\t\titemName3.setValue(comb6.text);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 保存手术申请\r\n");
      out.write("\tfunction save() {\r\n");
      out.write("\t\tvar form = new mini.Form(\"form1\");\r\n");
      out.write("\t\tvar data = form.getData();\r\n");
      out.write("\t\tif(data.opsState != \"APL\") {\r\n");
      out.write("\t\t\ttop.mini.showTips({content: \"手术申请已审核不可修改！\", state: \"warning\", x: \"center\", y: \"center\", timeout: 2000});\r\n");
      out.write("\t\t\treturn ; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdata.registerId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.registerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\tform.validate();\r\n");
      out.write("\t\tvar applyDeptId=top.orgCombo.value;\r\n");
      out.write("\t\tdata.applyDeptId=applyDeptId;\r\n");
      out.write("\t\tif (form.isValid()) {\r\n");
      out.write("\t\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/operation/outOpsApply/edit.do\";\r\n");
      out.write("\t\t\t$.post(url, data, function(r) {\r\n");
      out.write("\t\t\t\tif (r==\"ok\") {\r\n");
      out.write("\t\t\t\t\tgoodbye(\"ok\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ttop.mini.alert(r);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 设置诊断信息\r\n");
      out.write("\tfunction setDiagName() {\r\n");
      out.write("\t\tvar diagName = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.diagName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\tif(diagName.length > 15) {\r\n");
      out.write("\t\t\tdiagName = diagName.substring(0, 15) + \"......\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\".diagName\").html(diagName);\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write("\t// 取消\r\n");
      out.write("\tfunction cancel() {\r\n");
      out.write("\t\tgoodbye();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"padding:0;\">\r\n");
      out.write("\t<!-- !!checked by jack // form1-div应该可以省掉,以减少一层div,放到mini-fit上试一下 -->\r\n");
      out.write("\t<div id=\"form1\">\r\n");
      out.write("\t\t<input class=\"mini-hidden\" name=\"opsState\"/>\r\n");
      out.write("\t\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t\t<fieldset id=\"fd1\">\r\n");
      out.write("\t\t        <legend><span>患者信息</span></legend>\r\n");
      out.write("\t\t        <div class=\"fieldset-body\">\r\n");
      out.write("\t\t             <table style=\"width:100%;font-size:14px;\">\r\n");
      out.write("\t\t\t\t       <tr>\r\n");
      out.write("\t\t\t\t       \t\t<td>患者: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.patientName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" \r\n");
      out.write("\t\t\t\t\t       \t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t       \t\t<td>病历号:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.patientId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("\t\t\t\t       \t\t<td>挂号时间:  ");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("</td>\r\n");
      out.write("\t\t\t\t       </tr>\r\n");
      out.write("\t\t\t\t       <tr>\r\n");
      out.write("\t\t\t\t       \t\t<td>诊断:<span class=\"diagName\" data-tooltip=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.diagName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" data-placement=\"right\" style=\"color:#006aad;font-weight:bold;\"></span></td>\r\n");
      out.write("\t\t\t\t       \t\t<td>总费用: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.totCost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("(未缴：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.tag.unpayCost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" })</td>\r\n");
      out.write("\t\t\t\t       \t\t<td>门慢信息: 无</td>\r\n");
      out.write("\t\t\t\t       </tr>\r\n");
      out.write("\t\t\t\t    </table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </fieldset>\r\n");
      out.write("\t\t    <fieldset id=\"fd2\">\r\n");
      out.write("\t\t        <legend><span>诊断信息</span></legend>\r\n");
      out.write("\t\t        <div class=\"fieldset-body\">\r\n");
      out.write("\t\t            <table style=\"width:100%;font-size:14px;\">\r\n");
      out.write("\t\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t        \t<td class=\"shuName main\">术前诊断一：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo1\" class=\"mini-autocomplete\" style=\"width:95%;\" emptyText=\"请选择...\"   valueFromSelect=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\tvalueField=\"seqId\" allowInput=\"true\" name=\"diagId\"  \r\n");
      out.write("\t\t\t\t        \t\t\tonValuechanged = \"onDiagnoseValuechanged1\" required=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/ICD/getKVs.do?diagSysType=ICD10 \" />\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"diagName1\" class=\"mini-hidden\" name=\"diagName\" />\t\r\n");
      out.write("\t\t\t\t        \t\t<input class=\"mini-hidden\" name=\"applyId\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td class=\"shuName\">术前诊断二：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo2\" class=\"mini-autocomplete\" style=\"width:95%;\" emptyText=\"请选择...\" valueFromSelect=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\tvalueField=\"seqId\" allowInput=\"true\" name=\"diagId2\"\r\n");
      out.write("\t\t\t\t        \t\t\tonValuechanged = \"onDiagnoseValuechanged2\" \r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/ICD/getKVs.do?diagSysType=ICD10 \" />\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"diagName2\" class=\"mini-hidden\" name=\"diagName2\"/>\t\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t \t\t\t<td class=\"shuName\">术前诊断三：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo3\" class=\"mini-autocomplete\" style=\"width:95%;\" emptyText=\"请选择...\"   valueFromSelect=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\tvalueField=\"seqId\" allowInput=\"true\"  name=\"diagId3\"\r\n");
      out.write("\t\t\t\t        \t\t\tonValuechanged = \"onDiagnoseValuechanged3\" \r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/ICD/getKVs.do?diagSysType=ICD10 \" />\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"diagName3\" class=\"mini-hidden\" name = \"diagName3\" />\t\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t    </table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </fieldset>\r\n");
      out.write("\t\t    <fieldset id=\"fd3\">\r\n");
      out.write("\t\t        <legend><span>手术信息</span></legend>\r\n");
      out.write("\t\t        <div class=\"fieldset-body\">\r\n");
      out.write("\t\t             <table style=\"width:100%;font-size:14px;\">\r\n");
      out.write("\t\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t        \t<td class=\"shuName main\">拟手术名称：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input class=\"mini-autocomplete\" name=\"itemId\" id=\"combo4\" style=\"width:95%;\" emptyText=\"请选择...\"  valueFromSelect=\"true\" allowInput=\"true\" \r\n");
      out.write("\t\t\t\t        \t\t\tvalueField=\"id\" onValuechanged=\"onOperationValuechanged1\" required=\"true\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/basedata/datamanager/nondrug/getOpsNames.do\"/>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"itemName1\" class=\"mini-hidden\" name=\"itemName\"/>\t\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td class=\"shuName\">拟手术名称：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo5\" class=\"mini-autocomplete\" style=\"width:95%;\" emptyText=\"请选择...\"  valueFromSelect=\"true\" pinyinField=\"spellCode\"\r\n");
      out.write("\t\t\t\t        \t\t\tvalueField=\"id\" allowInput=\"true\" name=\"itemId2\" onValuechanged=\"onOperationValuechanged2\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/basedata/datamanager/nondrug/getOpsNames.do\" />\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"itemName2\" class=\"mini-hidden\" name=\"itemName2\"/>\t\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t \t\t\t<td class=\"shuName\">拟手术名称：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo6\" class=\"mini-autocomplete\" style=\"width:95%;\" emptyText=\"请选择...\" valueFromSelect=\"true\"   pinyinField=\"spellCode\"\r\n");
      out.write("\t\t\t\t        \t\t\tvalueField=\"id\" allowInput=\"true\" name = \"itemId3\" onValuechanged = \"onOperationValuechanged3\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/basedata/datamanager/nondrug/getOpsNames.do\"/>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"itemName3\" class=\"mini-hidden\" name=\"itemName3\" />\t\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t    </table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </fieldset>\r\n");
      out.write("\t\t    <fieldset id=\"fd4\">\r\n");
      out.write("\t\t        <legend><span>执行信息</span></legend>\r\n");
      out.write("\t\t        <div class=\"fieldset-body\">\r\n");
      out.write("\t\t            <table style=\"width:100%;font-size:14px; border-collapse:separate;border-spacing:9px;\" >\r\n");
      out.write("\t\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\" style=\"min-width:70px\">手术类别：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo7\" class=\"mini-combobox\" emptyText=\"请选择...\" name = \"opsKind\"\r\n");
      out.write("\t\t\t\t        \t\t\tdata=\"[{id:0,text:'0.非择期'},{id:1,text:'1.是择期'},]\" required=\"true\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">体 位：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo8\" class=\"mini-combobox\" emptyText=\"请选择...\" required=\"true\" name = \"tPosition\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_OPS_OPERBODY\"  />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">部 位：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo9\" class=\"mini-combobox\" emptyText=\"请选择...\" required=\"true\" name = \"bPosition\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_OPS_OPERPART\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t \t\t\t<td align=\"right\" class=\"main\" style=\"min-width:70px\">麻醉方式：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo10\" class=\"mini-combobox\" emptyText=\"请选择...\" name=\"anesWay\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_OPS_ANESTYPE\" required=\"true\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">台 类 型：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo13\" name=\"consoleType\" class=\"mini-combobox\" required=\"true\"  emptyText=\"请选择...\"\r\n");
      out.write("\t\t\t\t        \t\t\tdata=\"[{id:1,text:'普通'},{id:2,text:'加台'},{id:3,text:'点台'},{id:2,text:'加急台'}]\"/>\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">切口类型：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo23\" name=\"inciType\" class=\"mini-combobox\" emptyText=\"请选择...\" required=\"true\" \r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_OPS_INCITYPE\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">感染类型：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo11\" class=\"mini-combobox\" emptyText=\"请选择...\" name = \"injectionType\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_OPS_INFECTIONTYPE\" required=\"true\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">拟手术日期：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"date1\" name = \"applyTime\" class=\"mini-datepicker\"  format=\"yyyy-MM-dd HH:mm\" required=\"true\" showTime=\"true\"/>\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">台 序：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo12\" name=\"consoleId\" class=\"mini-combobox\" emptyText=\"请选择...\" required=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_OPS_OPERATIONORDER\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">手  术  者：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo14\" name=\"opsDoctorId\" class=\"mini-combobox\" emptyText=\"请选择...\" allowInput=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/basedata/employee/getKVs.do?employeeType=D\" required=\"true\" onvaluechanged=\"changeDept\"/>\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\">术者科室：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t\t<input id=\"combo15\" name=\"doctorDeptId\" class=\"mini-combobox\" allowInput=\"true\" emptyText=\"请选择...\"    \r\n");
      out.write("\t\t\t\t        \t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrgRelationShip/initDeptTree.do\"  required=\"true\" />\r\n");
      out.write("\t\t\t\t        \t\t\t\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\" class=\"main\"  style=\"min-width:70px\">手 术 室：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo16\" name=\"execDeptId\" class=\"mini-combobox\" emptyText=\"请选择...\" allowInput=\"true\"  \r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getOpsDept.do\" required=\"true\"/>\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\">一助手：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo17\" name=\"helper1\" class=\"mini-combobox\" emptyText=\"请选择...\" allowInput=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/basedata/employee/getKVs.do?employeeType=D\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\">二助手：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo18\" name=\"helper2\" class=\"mini-combobox\" emptyText=\"请选择...\" allowInput=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/basedata/employee/getKVs.do?employeeType=D\"  showTime=\"true\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\">三助手：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo19\" name=\"helper3\" class=\"mini-combobox\" emptyText=\"请选择...\" allowInput=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/basedata/employee/getKVs.do?employeeType=D\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\">拟持续时间：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"textbox1\"name=\"lastTime\" class=\"mini-textbox\" emptyText=\"2小时\" value=\"2小时\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td class=\"main\" align=\"right\">申  请  人：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo21\" name=\"applyDoctorId\" class=\"mini-combobox\" emptyText=\"请选择...\"  allowInput=\"true\" required=\"true\"\r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/basedata/employee/getKVs.do?employeeType=D\"  required=\"true\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\">手术级别：</td>\r\n");
      out.write("\t\t\t\t        \t<td>\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"combo22\" name=\"degree\" class=\"mini-combobox\" emptyText=\"请选择...\" \r\n");
      out.write("\t\t\t\t        \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_OPS_OPERATELEVEL\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t \t\t<tr>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\">申请日期：</td>\r\n");
      out.write("\t\t\t\t        \t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"textbox2\" name=\"createdTime\" class=\"mini-textbox\" readonly=\"true\" style=\"width:100%;\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t        \t<td align=\"right\">特殊说明：</td>\r\n");
      out.write("\t\t\t\t        \t<td colspan=\"4\" >\r\n");
      out.write("\t\t\t\t        \t\t<input id=\"textarea\" name=\"applyMemo\" class=\"mini-textarea\" emptyText=\"请输入特殊说明...\"style=\"width:100%;\" />\r\n");
      out.write("\t\t\t\t        \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t    </table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t    </fieldset>\r\n");
      out.write("\t\t    <div class=\"submintButton\">\r\n");
      out.write("\t\t    \t<span class=\"msg\">要求在11：00之前发送次日择期手术，否则将无法发送!</span>\r\n");
      out.write("\t\t    \t<a class=\"mini-button\" onclick=\"save\">保存</a> \r\n");
      out.write("\t\t    \t<a class=\"mini-button\" onclick=\"cancel\">取消</a>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tmini.parse();\r\n");
      out.write("\t\tvar tip = new mini.ToolTip();\r\n");
      out.write("\t\ttip.set({\r\n");
      out.write("\t\t    target: document,\r\n");
      out.write("\t\t    selector: '[data-tooltip], [title]'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ttip.setContent(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.diagName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\tsetDiagName();\r\n");
      out.write("\t\tquery();\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /commons/include/get.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /commons/include/get.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/get.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /commons/include/get.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("emr");
      // /commons/include/get.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/get.jsp(6,0) '${emrContextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${emrContextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t         \t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t         \t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/view/medical/operation/outOpsApplyUpdateView.jsp(167,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.sexCode =='1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('男');
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('女');
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/view/medical/operation/outOpsApplyUpdateView.jsp(173,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${register.registerTime}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/medical/operation/outOpsApplyUpdateView.jsp(173,24) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd HH:mm:ss");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
