/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-05-11 08:09:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.expense.outpatient.radt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class opRegisterCancel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525761782870L));
    _jspx_dependants.put("/commons/include/html_doctype.html", Long.valueOf(1525761798654L));
    _jspx_dependants.put("/commons/include/form.jsp", Long.valueOf(1525761798651L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>门诊退号</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<!-- <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" /> -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/default/css/web.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/boot.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/commons/dynamic.jsp\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/misc/jquery.form.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/core.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/report/CreateControl.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tfieldset {\r\n");
      out.write("\t    border: solid 1px #c5c5c5;\r\n");
      out.write("\t}\r\n");
      out.write("\t.required {\r\n");
      out.write("\t\tcolor:#006aad;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.mini-splitter .mini-splitter-pane2 {\r\n");
      out.write("\t    border: 0px solid #9f4848;\r\n");
      out.write("\t    background: #fff;\r\n");
      out.write("\t    border-radius: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t//清空页面\r\n");
      out.write("\tfunction clear(e){\r\n");
      out.write("\t\tgrid1.clearRows();\r\n");
      out.write("\t\tgrid2.clearRows();\r\n");
      out.write("\t\tgrid3.clearRows();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 按条件查询挂号信息\r\n");
      out.write("\tfunction getByKey(e) {\r\n");
      out.write("\t\tclear();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar key = mini.get(\"key\").getValue();\r\n");
      out.write("\t\tif(!key) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar text = $(\"#text01\").text();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tswitch(num)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\tcase 1:\r\n");
      out.write("\t\t\tgetByIdnetifierNo(key, text);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 2:\r\n");
      out.write("\t\t\tgetBySerialId(key);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 3:\r\n");
      out.write("\t\t\tqueryByPatientId(key);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 4:\r\n");
      out.write("\t\t\tgetByName(key, text);\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 根据姓名查询患者信息\r\n");
      out.write("\tfunction getByName(key, text) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/patient/getByNameOrPhone.do\";\r\n");
      out.write("\t\tvar data = {patientName : key};\r\n");
      out.write("\t\t$.post(url, data , function(r) {\r\n");
      out.write("\t\t\tvar count = r.length;\r\n");
      out.write("\t\t\tif(count == 0){\r\n");
      out.write("\t\t\t\tmini.alert(\"没有找到 \"+ text +\" 为：\"+ key +\" 的患者信息\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(count == 1) { // 如果根key只查到一条信息，直接回填\r\n");
      out.write("\t\t\t\tvar patientId = r[0].patientId;\r\n");
      out.write("\t\t\t\tqueryByPatientId(patientId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(count > 1) { // 如果根据key查到多条信息，弹出供选择\r\n");
      out.write("\t\t\t\tgrid4.setData(r);\r\n");
      out.write("\t\t\t\twin.setTitle(\"选择患者\");\r\n");
      out.write("\t\t\t\twin.show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 根据证件号 查询患者信息\r\n");
      out.write("\tfunction getByIdnetifierNo(key, text) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/patient/getByNameOrPhone.do\";\r\n");
      out.write("\t\tvar data = {idnetifierNo : key};\r\n");
      out.write("\t\t$.post(url, data , function(r) {\r\n");
      out.write("\t\t\tvar count = r.length;\r\n");
      out.write("\t\t\tif(count == 0){\r\n");
      out.write("\t\t\t\tmini.alert(\"没有找到 \"+ text +\" 为：\"+ key +\" 的患者信息\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(count == 1) { // 如果根key只查到一条信息，直接回填\r\n");
      out.write("\t\t\t\tvar patientId = r[0].patientId;\r\n");
      out.write("\t\t\t\tqueryByPatientId(patientId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(count > 1) { // 如果根据key查到多条信息，弹出供选择\r\n");
      out.write("\t\t\t\tgrid4.setData(r);\r\n");
      out.write("\t\t\t\twin.setTitle(\"选择患者\");\r\n");
      out.write("\t\t\t\twin.show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 根据当日号查询挂号记录\r\n");
      out.write("\tfunction getBySerialId(e) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/getBySerialId.do\";\r\n");
      out.write("\t\tvar data = {dailySerialId : e};\r\n");
      out.write("\t\t$.post(url, data , function(r) {\r\n");
      out.write("\t\t\tvar count = r.length;\r\n");
      out.write("\t\t\tif(count == 0) {\r\n");
      out.write("\t\t\t\tmini.alert(\"没有找到有效的挂号记录\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tgrid1.setData(r);\r\n");
      out.write("\t\t\tonload();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// window 弹出框查询患者\r\n");
      out.write("\tfunction queryRegister(e) {\r\n");
      out.write("\t\tgrid4.load({\r\n");
      out.write("\t\t\tkey : mini.get(\"key\").getValue(),\r\n");
      out.write("\t\t\tregisterTime : mini.formatDate (new Date(), \"yyyy-MM-dd\")\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 双击选中患者\r\n");
      out.write("\tfunction selected(e) {\r\n");
      out.write("\t\tqueryByPatientId(e.row.patientId);\r\n");
      out.write("\t\twin.hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 根据病人唯一号查询挂号记录patientId\r\n");
      out.write("\tfunction queryByPatientId(e) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/getValidList.do\";\r\n");
      out.write("\t\tvar data = {patientId : e};\r\n");
      out.write("\t\t$.post(url, data , function(r) {\r\n");
      out.write("\t\t\tvar count = r.length;\r\n");
      out.write("\t\t\tif(count == 0) {\r\n");
      out.write("\t\t\t\tmini.alert(\"没有找到有效的挂号记录\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tgrid1.setData(r);\r\n");
      out.write("\t\t\tonload();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar num = 2 ;\t\r\n");
      out.write("\t// 按F2切换检索条件\r\n");
      out.write("\tdocument.onkeydown=function(){\r\n");
      out.write("\t\t if(event.keyCode==113) {\r\n");
      out.write("\t\t\t switch(num)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\tcase 1:\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('text01').innerText = '当日号';\r\n");
      out.write("\t\t\t\t\tnum = 2 ;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 2:\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('text01').innerText = '唯一号';\r\n");
      out.write("\t\t\t\t\tnum = 3 ;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 3:\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('text01').innerText = '姓　名';\r\n");
      out.write("\t\t\t\t\tnum = 4 ;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 4:\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('text01').innerText = '证件号';\r\n");
      out.write("\t\t\t\t\tnum = 1 ;\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\t}\r\n");
      out.write("\t// 根据发票号查询挂号信息\r\n");
      out.write("\tfunction queryByReceiptNo(e) {\r\n");
      out.write("\t\tclear();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar receiptNo = mini.get(\"receiptNo01\").getValue();\r\n");
      out.write("\t\tif(!receiptNo) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgrid1.load({receiptNo : receiptNo});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 根据系列号(收据ID) 查询挂号信息\r\n");
      out.write("\tfunction queryByReceiptId(e){\r\n");
      out.write("\t\tclear();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar receiptId = mini.get(\"receiptId01\").getValue();\r\n");
      out.write("\t\tif(!receiptId){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgrid1.load({receiptId : receiptId});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 挂号信息加载完成时\r\n");
      out.write("\tfunction onload() {\r\n");
      out.write("\t\tif(grid1.getList().length == 0) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar row = grid1.getRow(0);\r\n");
      out.write("\t\tgrid1.setSelected(row);\r\n");
      out.write("\t\tgrid3.load({\r\n");
      out.write("\t\t\treceiptId : row.tag.receiptId\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgrid2.load({\r\n");
      out.write("\t\t\tregisterId : row.registerId,\r\n");
      out.write("\t\t\tbalanceId : row.balanceId\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 选中挂号信息时, 显示费用信息和支付方式\r\n");
      out.write("\tfunction onSelected(e) {\r\n");
      out.write("\t\tvar row = grid1.getSelected();\t\t\r\n");
      out.write("\t\tgrid3.load({\r\n");
      out.write("\t\t\treceiptId : row.tag.receiptId\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgrid2.load({\r\n");
      out.write("\t\t\tregisterId : row.registerId,\r\n");
      out.write("\t\t\tbalanceId : row.balanceId\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 退号\r\n");
      out.write("\tfunction save(e){\r\n");
      out.write("\t\tvar row = grid1.getSelected();\r\n");
      out.write("\t\tif(!row){\r\n");
      out.write("\t\t\tmini.alert(\"请先选择列表中的患者信息\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar data = row;\r\n");
      out.write("\t\tdata.paymentBase = grid3.getList();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmini.open({\r\n");
      out.write("\t        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/radt/opRegister/cancelConfirm.do\",\r\n");
      out.write("\t        title: \"选择支付方式\", \r\n");
      out.write("\t        width: 700, \r\n");
      out.write("\t        height: 500,\r\n");
      out.write("\t        onload : function(r) {\r\n");
      out.write("\t        \tvar iframe = this.getIFrameEl();\r\n");
      out.write("\t    \t\tiframe.contentWindow.setData(data);\r\n");
      out.write("\t        },\r\n");
      out.write("\t        ondestroy: function (r) {\r\n");
      out.write("\t        \tif (r.type == \"ok\") {\r\n");
      out.write("\t        \t\tvar data2 = {\r\n");
      out.write("\t        \t\t\tregisterId : row.registerId,\r\n");
      out.write("\t        \t\t\treceiptId : row.tag.receiptId,\r\n");
      out.write("\t        \t\t\tpaymentList : mini.encode(r.paymentList)\r\n");
      out.write("\t        \t\t};\r\n");
      out.write("\t        \t\tdoSave(data2);\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t    }); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 确认后执行退号\r\n");
      out.write("\tfunction doSave(e) {\r\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/cancelRegister.do\";\r\n");
      out.write("\t\t$.post(url, e, function (r) {\r\n");
      out.write("\t\t\tif(r == \"ok\") {\r\n");
      out.write("\t\t\t\tclear();\r\n");
      out.write("\t\t\t\tmini.showTips({content:\"退号成功!\",state:\"success\",x:\"center\",y:\"center\",timeout:3000});\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tmini.alert(r);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 执行打印\r\n");
      out.write("\tfunction execPrint(row){\r\n");
      out.write("\t\tvar json;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/radt/opRegister/printRegisteredInvoice.do\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tregisterId:row.registerId\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tasync: false,\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\tjson = data;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tReport.LoadFromURL(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/report/template/registeredInvoice.grf?t=\"+new Date().getTime());//加载报表\r\n");
      out.write("\t\t\t\tReport.PrepareLoadData();\r\n");
      out.write("\t\t\t\tvar registerTime = \"\";\r\n");
      out.write("\t\t\t\tif (json.registerTime) {\r\n");
      out.write("\t\t\t\t\tregisterTime = json.registerTime;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"registerTime\").AsString = registerTime;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"patientId\").AsString = json.patientId;\r\n");
      out.write("\t\t\t \tReport.ParameterByName(\"appointmentID\").AsString = json.appointmentID;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"age\").AsString = json.age;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"num\").AsString = json.num;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"dailySerialId\").AsString = json.dailySerialId;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"patientName\").AsString = json.patientName;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"place\").AsString = json.place;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"registerDept\").AsString = json.registerDept;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"registerTime\").AsString = registerTime;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"reglevel\").AsString = json.reglevel;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"staff\").AsString = json.staff;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"sex\").AsString = json.sex;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"staff\").AsString = json.staff;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"time\").AsString = json.time;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"createTime\").AsString = json.createTime;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"price1\").AsString = json.price1;\r\n");
      out.write("\t\t\t\tReport.ParameterByName(\"price2\").AsString = json.price2;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("// \t\t\t\tReport.Print(false);// false为直接打印\r\n");
      out.write("\t\t\t\tReport.PrintPreview(true);// 打印预览\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//发票跳号\r\n");
      out.write("\tfunction invoiceJumpNumber(row){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/radt/opRegister/invoiceJumpNumber.do\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tregisterId:row.registerId,\r\n");
      out.write("\t\t\t\treceiptNo:row.tag.receiptNo\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tasync: false\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 重打挂号票\r\n");
      out.write("\tfunction rePrintInvoice() {\r\n");
      out.write("\t\tvar row = grid1.getSelected();\r\n");
      out.write("\t\tif(!row) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar message = \"确认重打患者[\" +row.patientName+\"]的挂号收据？\\n请注意：重打时，发票跳号！！！！！！！ \";\r\n");
      out.write("\t\tmini.confirm(message,\"请选择！\",\r\n");
      out.write("\t\t\tfunction(action){\r\n");
      out.write("\t\t\t\tif(action == \"ok\"){\r\n");
      out.write("\t\t\t\t\tinvoiceJumpNumber(row);\t//发票跳号\r\n");
      out.write("\t\t\t\t\tgetByKey();\t\t\t//必须刷新datagrid，否则下次操作同一条数据时会因为receiptNo没有刷新出错\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t \texecPrint(row); \t\t//打印发票\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction show() {\r\n");
      out.write("\t\t$(\".hideBegin\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar sexType = [{id:\"1\",text:\"男\"}, {id:\"2\",text:\"女\"}];\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"mini-toolbar hideBegin\" style=\"display:none;\">\r\n");
      out.write("\t\t<span id=\"text01\" style=\"font-size:14px;color:#006aad;font-weight:bold;\">当日号 </span>\r\n");
      out.write("\t\t<input id=\"key\" class=\"mini-textbox\" emptyText=\"按F2切换检索条件\" width=\"200\" onenter=\"getByKey\"/>\r\n");
      out.write("\t\t<span>系列号:</span>\r\n");
      out.write("\t\t<input id=\"receiptId01\" class=\"mini-textbox\" emptyText=\"收据ID\" onenter=\"queryByReceiptId\"/>\r\n");
      out.write("\t\t<span>发票号:</span>\r\n");
      out.write("\t\t<input id=\"receiptNo01\" class=\"mini-textbox\" onenter=\"queryByReceiptNo\"/>\r\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-save\" onclick=\"save\">退号</a>\r\n");
      out.write("\t    <a class=\"mini-button\" iconCls=\"fa fa-window-print\" onclick=\"rePrintInvoice()\">重打挂号票</a>\r\n");
      out.write("\t    <a class=\"mini-button\" iconCls=\"fa fa-remove\" onclick=\"clear()\">清空</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t<div class=\"mini-splitter hideBegin\" style=\"width:100%;height:100%;\" vertical=\"true\" \r\n");
      out.write("\t\t\tallowResize=\"false\" handlerSize=\"6\" >\r\n");
      out.write("\t\t\t<div size=\"35%\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t<div id=\"grid1\" class=\"mini-datagrid\" showPager=\"false\" borderStyle=\"border:0;\" \r\n");
      out.write("\t\t\t\t\tstyle=\"width:100%;height:100%;\" selectOnLoad=\"true\" onselect=\"onSelected\" \r\n");
      out.write("\t\t    \t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/getValidList.do\">\r\n");
      out.write("\t\t\t\t\t <div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t \t<div field=\"dailySerialId\" headerAlign=\"center\" align=\"center\" width=\"50\">当日号</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"patientId\" headerAlign=\"center\" align=\"center\" width=\"90\">唯一号</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"tag.receiptNo\" headerAlign=\"center\" align=\"center\" width=\"80\">发票号</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"patientName\" headerAlign=\"center\" align=\"center\" width=\"60\">患者姓名</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"sexCode\" headerAlign=\"center\" align=\"center\" type=\"comboboxcolumn\" width=\"35\">性别\r\n");
      out.write("\t\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" data=\"sexType\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"idnetifierNo\" headerAlign=\"center\" align=\"center\" width=\"120\">证件号码</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"age\" headerAlign=\"center\" align=\"center\" width=\"35\">年龄</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"reglevelId\" type=\"comboboxColumn\" width=\"90\" headerAlign=\"center\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t \t\t挂号级别 <input property=\"editor\" class=\"mini-combobox\" textField=\"text\" valueField=\"id\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/maintenance/register/regLevel/getKVs.do\"/>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"registerDeptId\" headerAlign=\"center\" align=\"center\" type=\"comboboxcolumn\">科室\r\n");
      out.write("\t\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" style=\"width:100%;\" \r\n");
      out.write("\t\t\t\t \t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrgRelationShip/getTree.do\"  \r\n");
      out.write("\t\t\t\t \t\t\t\tvalueField=\"orgId\" textField=\"orgName\"/>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"registerDoctId\" headerAlign=\"center\" align=\"center\" type=\"comboboxcolumn\" width=\"60\">医生\r\n");
      out.write("\t\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" style=\"width:100%;\" \r\n");
      out.write("\t\t\t\t \t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/basedata/employee/getKVs.do?employeeType=D\"/>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t \t<div field=\"registerTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd\" width=\"70\">挂号日期</div>\r\n");
      out.write("\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t \t<div field=\"seeDoctId\" headerAlign=\"center\" align=\"center\" type=\"comboboxcolumn\" width=\"60\">看诊医生\r\n");
      out.write("\t\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" style=\"width:100%;\" \r\n");
      out.write("\t\t\t\t \t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/basedata/employee/getKVs.do?employeeType=D\"/>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"validFlag\" headerAlign=\"center\" align=\"center\" type=\"comboboxcolumn\" width=\"35\">有效\r\n");
      out.write("\t\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" data=\"[{id:'1',text:'有效'}, {id:'0',text:'无效'}]\" style=\"width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"tag.ownCost\" headerAlign=\"center\" align=\"center\" width=\"35\">金额</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"tag.receiptId\" headerAlign=\"center\" align=\"center\">收据ID</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"registerId\" visible=\"false\">门诊登记ID（隐藏）</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"balanceId\" visible=\"false\">结算ID（隐藏）</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"tag.medicaltypeName\" visible=\"false\">结算(医保)类别名称（隐藏）</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"totCost\" visible=\"false\">（隐藏）</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"tag.pubCost\" visible=\"false\">（隐藏）</div>\r\n");
      out.write("\t\t\t\t\t \t<div field=\"seeFlag\" visible=\"false\">（隐藏）</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t<div class=\"mini-splitter\" style=\"width:100%;height:100%;\" allowResize=\"false\" \r\n");
      out.write("\t\t\t\t\thandlerSize=\"6\">\r\n");
      out.write("\t\t\t\t\t<div size=\"50%\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"grid2\" class=\"mini-datagrid\" showPager=\"false\" style=\"width:100%;height:100%;\" borderStyle=\"border:0;\" \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/getByKeys.do\">\r\n");
      out.write("\t\t\t\t\t\t\t <div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t \t<div field=\"tag.itemFeeType\" visible=\"true\">类别(<span style=\"color:red;font-weight:bold;\">费用信息</span>)\r\n");
      out.write("\t\t\t\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_ITEMFEETYPE\"/>\r\n");
      out.write("\t\t\t\t\t\t\t \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t<div field=\"itemName\">名称</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t<div field=\"qty\" visible=\"false\">数量</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t<div field=\"totCost\">金额</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div size=\"50%\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"grid3\" class=\"mini-datagrid\" showPager=\"false\" style=\"width:100%;height:100%;\" \r\n");
      out.write("\t\t\t\t\t\t\t url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/OpExpReceiptPayment/getByReceiptId.do\">\r\n");
      out.write("\t\t\t\t\t\t\t <div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t \t<div field=\"paymentId\" visible=\"false\">支付方式ID</div>\r\n");
      out.write("\t\t\t\t\t\t\t \t<div field=\"paymentName\" headerAlign=\"center\" align=\"center\"><span style=\"color:red;font-weight:bold;\">支付方式</span></div>\r\n");
      out.write("\t\t\t\t\t\t\t \t<div field=\"actualCost\" headerAlign=\"center\" align=\"center\">金额</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"mini-window\" id=\"win1\" style=\"display:none;width:50%;height:50%;\" >\r\n");
      out.write("\t\t<div class=\"mini-fit\">\r\n");
      out.write("\t        <div id=\"grid4\" class=\"mini-datagrid\" style=\"width:100%;height:100%;\"  allowResize=\"true\"\r\n");
      out.write("\t        \turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/getByKeys.do\" borderStyle=\"border:0;\"  \r\n");
      out.write("\t            onrowdblclick=\"selected\">\r\n");
      out.write("\t            <div property=\"columns\">\r\n");
      out.write("\t                <div field=\"patientId\"  headerAlign=\"center\" align=\"center\">唯一号</div>\r\n");
      out.write("\t                <div field=\"inpatientNo\"  headerAlign=\"center\" align=\"center\">住院号</div>\r\n");
      out.write("\t                <div field=\"patientName\" headerAlign=\"center\" align=\"center\">患者姓名</div>    \r\n");
      out.write("\t                <div field=\"sexCode\" type=\"comboboxcolumn\" headerAlign=\"center\" align=\"center\">性别\r\n");
      out.write("\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" style=\"width:100%;\" data=\"sexType\"/>\r\n");
      out.write("\t\t\t\t \t</div>                                            \r\n");
      out.write("\t                <div field=\"age\" headerAlign=\"center\" align=\"center\">年龄</div>\r\n");
      out.write("\t                <div field=\"idnetifierTypeId\" type=\"comboboxcolumn\" headerAlign=\"center\" align=\"center\">证件类型\r\n");
      out.write("\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" style=\"width:100%;\" \r\n");
      out.write("\t\t\t\t \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysDict/getKVs.do?dictType=BD_IDENTIFIER_TYPE\"/>\r\n");
      out.write("\t\t\t\t \t</div>\r\n");
      out.write("\t                <div field=\"idnetifierNo\" headerAlign=\"center\" align=\"center\" width=\"150\">证件号</div>\r\n");
      out.write("\t                <div field=\"phone\" headerAlign=\"center\" align=\"center\">电话</div>\r\n");
      out.write("\t                <div field=\"address\" headerAlign=\"center\" align=\"center\">现住地址</div> \r\n");
      out.write("\t                <div field=\"deptId\" headerAlign=\"center\" align=\"center\" type=\"comboboxcolumn\">科室\r\n");
      out.write("\t\t\t\t \t\t<input property=\"editor\" class=\"mini-combobox\" style=\"width:100%;\" \r\n");
      out.write("\t\t\t\t \t\t\turl=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do?orgType=I\"/>\r\n");
      out.write("\t\t\t\t \t</div> \r\n");
      out.write("\t                <div field=\"admitTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\">入院时间</div>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>   \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"display:block;margin-top:-16\">\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tCreateReport(\"Report\");\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tmini.parse();\r\n");
      out.write("\t\tvar grid1 = mini.get(\"grid1\");\r\n");
      out.write("\t\tvar grid2 = mini.get(\"grid2\");\r\n");
      out.write("\t\tvar grid3 = mini.get(\"grid3\");\r\n");
      out.write("\t\tvar grid4 = mini.get(\"grid4\");\r\n");
      out.write("\t\tvar win = mini.get(\"win1\");\r\n");
      out.write("\t\tmini.get(\"key\").focus();\r\n");
      out.write("\t\tshow();\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /commons/include/form.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /commons/include/form.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/form.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /commons/include/form.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("ctx_rpt");
      // /commons/include/form.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/form.jsp(6,0) '${reportContextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${reportContextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
