/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-05-14 08:21:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.medical.outpatient;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class opInjectCancelRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525761782870L));
    _jspx_dependants.put("/commons/include/html_doctype.html", Long.valueOf(1525761798654L));
    _jspx_dependants.put("/commons/include/form.jsp", Long.valueOf(1525761798651L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>取消注射登记</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<!-- <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" /> -->\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/default/css/web.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/boot.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/commons/dynamic.jsp\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/misc/jquery.form.js\"></script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/core.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.bottom_border {\r\n");
      out.write("\t\tborder-bottom : 1px solid #ccc;\r\n");
      out.write("\t\tpadding: 3px 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.mini-toolbar {\r\n");
      out.write("\t    border-bottom: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.sameWidth {\r\n");
      out.write("\t\twidth : 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t// 点击查询\r\n");
      out.write("\tfunction search() {\r\n");
      out.write("\t\tvar dataOrig = form.getData(); \r\n");
      out.write("\t\tvar data = {\r\n");
      out.write("\t\t\t\trecipeId : dataOrig.recipeId,\r\n");
      out.write("\t\t\t\tpatientId : dataOrig.patientId,\r\n");
      out.write("\t\t\t\tpatientName : dataOrig.patientName\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 可选条件(登记人)\r\n");
      out.write("\t\tif(dataOrig.bookOperIdValid == \"true\") {\r\n");
      out.write("\t\t\tdata.bookOperId = dataOrig.bookOperId;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 登记日期\r\n");
      out.write("\t\tif(dataOrig.bookOperTimeValid == \"true\") {\r\n");
      out.write("\t\t\tdata.bookTime = mini.formatDate(dataOrig.bookTime, \"yyyy-MM-dd\"); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 配药护士\r\n");
      out.write("\t\tif(dataOrig.mixOperIdValid == \"true\") {\r\n");
      out.write("\t\t\tdata.mixOperId = dataOrig.mixOperId; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 配药日期\r\n");
      out.write("\t\tif(dataOrig.mixOperTimeValid == \"true\") {\r\n");
      out.write("\t\t\tdata.mixOperTime = mini.formatDate(dataOrig.mixOperTime, \"yyyy-MM-dd\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 注射护士\r\n");
      out.write("\t\tif(dataOrig.injectOperIdValid == \"true\") {\r\n");
      out.write("\t\t\tdata.injectOperId = dataOrig.injectOperId; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 注射日期\r\n");
      out.write("\t\tif(dataOrig.injectOperTimeValid ==  \"true\") {\r\n");
      out.write("\t\t\tdata.injectOperTime = mini.formatDate(dataOrig.injectOperTime, \"yyyy-MM-dd\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgrid.load(data);\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t// 复选框选中事件\r\n");
      out.write("\tfunction onvaluechanged(num) {\r\n");
      out.write("\t\tswitch(num) {\r\n");
      out.write("\t\tcase 1:\r\n");
      out.write("\t\t\tmini.get(\"bookOperId\").set({enabled : !mini.get(\"bookOperId\").enabled});\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 2:\r\n");
      out.write("\t\t\tmini.get(\"bookTime\").set({enabled : !mini.get(\"bookTime\").enabled});\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 3:\r\n");
      out.write("\t\t\tmini.get(\"mixOperId\").set({enabled : !mini.get(\"mixOperId\").enabled});\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 4:\r\n");
      out.write("\t\t\tmini.get(\"mixOperTime\").set({enabled : !mini.get(\"mixOperTime\").enabled});\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 5:\r\n");
      out.write("\t\t\tmini.get(\"injectOperId\").set({enabled : !mini.get(\"injectOperId\").enabled});\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\tcase 6:\r\n");
      out.write("\t\t\tmini.get(\"injectOperTime\").set({enabled : !mini.get(\"injectOperTime\").enabled});\r\n");
      out.write("\t\t\tbreak;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 设置日期\r\n");
      out.write("\tfunction setTime() {\r\n");
      out.write("\t\tvar todayStr = mini.formatDate(new Date(), \"yyyy-MM-dd\");\r\n");
      out.write("\t\tvar todayTime = mini.parseDate(todayStr);\r\n");
      out.write("\t\tbookTime.setValue(todayTime);\r\n");
      out.write("\t\tmixOperTime.setValue(todayTime);\r\n");
      out.write("\t\tinjectOperTime.setValue(todayTime);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 全选\r\n");
      out.write("\tfunction selectAll() {\r\n");
      out.write("\t\tgrid.selectAll(true);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 全不选\r\n");
      out.write("\tfunction deselectAll() {\r\n");
      out.write("\t\tgrid.deselectAll(true);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 取消登记\r\n");
      out.write("\tfunction cancelInjectBook() {\r\n");
      out.write("\t\tvar rows = grid.getSelecteds();\r\n");
      out.write("\t\tvar injectIdArr = [];\r\n");
      out.write("\t\tvar applyIdArr = [];\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i = 0; i < rows.length; i++) {\r\n");
      out.write("\t\t\tinjectIdArr.push(rows[i].injectId);\r\n");
      out.write("\t\t\tapplyIdArr.push(rows[i].applyId);\r\n");
      out.write("\t\t}\r\n");
      out.write("// \t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opInject/cancelInject.do\";\r\n");
      out.write("// \t\tvar fn = function(r) {\r\n");
      out.write("// \t\t\tif(r == \"ok\") {\r\n");
      out.write("// \t\t\t\tmini.showTips({\r\n");
      out.write("//             \t\tcontent: \"取消注射登记操作成功\",    \r\n");
      out.write("//             \t    state: \"success\",      \r\n");
      out.write("//             \t    x: \"center\",          \r\n");
      out.write("//             \t    y: \"center\",          \r\n");
      out.write("//             \t\ttimeout: 2000\r\n");
      out.write("//            \t \t});\r\n");
      out.write("// \t\t\t\tsearch();\r\n");
      out.write("// \t\t\t} else {\r\n");
      out.write("// \t\t\t\ttop.mini.error(r, \"提示\");\r\n");
      out.write("// \t\t\t}\r\n");
      out.write("// \t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("// \t\t$.post(url, {injectIds: injectIdArr.join(\",\"), \r\n");
      out.write("// \t\t\t\t\t applyIds: applyIdArr.join(\",\") }, fn);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opInject/cancelInject.do\",\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tinjectIds: injectIdArr.join(\",\"), \r\n");
      out.write("\t\t\t\t applyIds: applyIdArr.join(\",\")\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(r){\r\n");
      out.write("\t\t\t\tif(r == \"ok\") {\r\n");
      out.write("\t\t\t\t\tmini.showTips({\r\n");
      out.write("\t            \t\tcontent: \"取消注射登记操作成功\",    \r\n");
      out.write("\t            \t    state: \"success\",      \r\n");
      out.write("\t            \t    x: \"center\",          \r\n");
      out.write("\t            \t    y: \"center\",          \r\n");
      out.write("\t            \t\ttimeout: 2000\r\n");
      out.write("\t           \t \t});\r\n");
      out.write("\t\t\t\t\tsearch();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\ttop.mini.error(r, \"提示\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction dailyIdRenderer(e){\r\n");
      out.write("\t\tvar dailySerialId  = e.record.dailySerialId;\r\n");
      out.write("\t\tvar orderExecuteTime = e.record.orderExecuteTime;\r\n");
      out.write("\t\tvar fmtDate = mini.formatDate(orderExecuteTime, \"MMdd\");\r\n");
      out.write("\t\treturn fmtDate + \"-\" + dailySerialId;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction drugRenderer(e){\r\n");
      out.write("\t\tvar drugName  = e.record.drugName;\r\n");
      out.write("\t\tvar drugSpecs = e.record.drugSpecs; \r\n");
      out.write("\t\treturn drugName +\"[\"+ drugSpecs+\"]\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction dosageRenderer(e){\r\n");
      out.write("\t\tvar orderOnceDosage  = e.record.orderOnceDosage;\r\n");
      out.write("\t\tvar orderOnceDosageUnit = e.record.orderOnceDosageUnit;\r\n");
      out.write("\t\treturn orderOnceDosage + orderOnceDosageUnit;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"mini-fit\">\r\n");
      out.write("\t\t<div class=\"mini-splitter\" style=\"width:100%;height:100%;\" allowResize=\"false\" handlerSize=\"-1\" borderStyle=\"border-top:0;\">\r\n");
      out.write("\t\t    <div size=\"280px;\" showCollapseButton=\"false\">\r\n");
      out.write("\t\t    \t\t<div id=\"form1\">\r\n");
      out.write("\t\t\t    \t\t<table style=\"padding:10px;\">\r\n");
      out.write("\t\t\t    \t\t\t<tr><td>处 方 号:</td><td><input class=\"mini-textbox\" name=\"recipeId\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td>病 人 号:</td><td> <input class=\"mini-textbox\" name=\"patientId\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td>姓　　名:</td><td> <input class=\"mini-textbox\" name=\"patientName\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td><input class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged(1)\" name=\"bookOperIdValid\"/>登  记  人:</td><td><input class=\"mini-combobox\" id=\"bookOperId\" name=\"bookOperId\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do?employeeType=D\" enabled=\"false\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td><input class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged(2)\" name=\"bookOperTimeValid\" value=\"true\"/>登记日期:</td><td><input class=\"mini-datepicker\" id=\"bookTime\" name=\"bookTime\" enabled=\"true\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td><input class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged(3)\" name=\"mixOperIdValid\"/>配药护士:</td><td><input class=\"mini-combobox\" id=\"mixOperId\" name=\"mixOperId\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do?employeeType=N\" enabled=\"false\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td><input class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged(4)\" name=\"mixOperTimeValid\"/>配药日期:</td><td><input class=\"mini-datepicker\" id=\"mixOperTime\" name=\"mixOperTime\" enabled=\"false\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td><input class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged(5)\" name=\"injectOperIdValid\"/>注射护士:</td><td><input class=\"mini-combobox\" id=\"injectOperId\" name=\"injectOperId\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do?employeeType=N\" enabled=\"false\"/></td></tr>\r\n");
      out.write("\t\t\t\t    \t\t<tr><td><input class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged(6)\" name=\"injectOperTimeValid\"/>注射日期:</td><td><input class=\"mini-datepicker\" id=\"injectOperTime\" name=\"injectOperTime\" enabled=\"false\"/></td></tr>\r\n");
      out.write("\t\t\t    \t\t</table>\r\n");
      out.write("\t\t    \t\t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t    <div showCollapseButton=\"false\">\r\n");
      out.write("\t\t\t    <div class=\"mini-toolbar\" borderStyle=\"border-top:0;border-right:0;border-left:0;border-bottom:1;\">\r\n");
      out.write("\t\t\t\t    <table style=\"width:100%;\">\r\n");
      out.write("\t\t\t\t        <tr>\r\n");
      out.write("\t\t\t\t         \t<td colspan=\"5\">\r\n");
      out.write("\t\t\t\t         \t\t<a class=\"mini-button\" iconCls=\"fa fa-search\" onclick=\"search\">查询</a>\r\n");
      out.write("\t\t\t\t         \t\t<a class=\"mini-button\" iconCls=\"fa fa-plus-square\" onclick=\"selectAll\">全选</a>\r\n");
      out.write("\t\t\t\t         \t\t<a class=\"mini-button\" iconCls=\"fa fa-remove\" onclick=\"deselectAll\">全不选</a>\r\n");
      out.write("\t\t\t\t         \t\t<a class=\"mini-button\" iconCls=\"\" onclick=\"cancelInjectBook\">取消登记</a>\r\n");
      out.write("\t\t\t\t         \t\t<a class=\"mini-button\" iconCls=\"\" onclick=\"\">打印瓶签</a>\r\n");
      out.write("\t\t\t\t         \t\t<a class=\"mini-button\" iconCls=\"\" onclick=\"\">打印输液卡</a>\r\n");
      out.write("\t\t\t\t         \t</td>\r\n");
      out.write("\t\t\t\t \t\t</tr>\r\n");
      out.write("\t\t\t\t    </table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t    <div class=\"mini-fit\">\r\n");
      out.write("\t\t\t         <div id=\"grid1\" class=\"mini-datagrid\" borderStyle=\"border:0;border-top:1px solid #ccc;\" allowCellSelect=\"true\" idField=\"itemNo\" \r\n");
      out.write("\t\t\t         \t style=\"height:100%;\" allowCellEdit=\"true\" multiSelect=\"true\" allowUnselect=\"true\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/outpatient/opExpApply/getInjectsInfo.do\">\r\n");
      out.write("\t\t\t\t\t\t <div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t \t<div type=\"checkColumn\"></div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"dailySerialId\" name=\"dailySerialId\" headerAlign=\"center\" width=\"50\" align=\"center\" renderer=\"dailyIdRenderer\">当日号</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"patientId\" headerAlign=\"center\" align=\"center\">病人号</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"patientName\" headerAlign=\"center\" align=\"center\">患者姓名</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"recipeDoctName\" headerAlign=\"center\" align=\"center\">开单医生</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"recipeDeptName\" headerAlign=\"center\" align=\"center\">开单科室</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"drugName\" headerAlign=\"center\" align=\"center\" width=\"250\" rendere\tr=\"drugRenderer\">医嘱</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"drugSpecs\" headerAlign=\"center\" align=\"center\"visible=\"false\">单位</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"orderCombId\" headerAlign=\"center\" align=\"center\">组合</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"orderOnceDosage\" headerAlign=\"center\" align=\"center\" renderer=\"dosageRenderer\" dataType=\"float\">每次量</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"orderOnceDosageUnit\" headerAlign=\"center\" align=\"center\" visible=\"false\">每次量单位</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"orderFrequency\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">频次\r\n");
      out.write("\t\t\t\t\t        \t<div property=\"editor\" class=\"mini-combobox\" popupWidth=\"400\" required=\"true\" \r\n");
      out.write("\t\t\t\t\t\t\t\t \t  allowInput=\"true\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/frequency/getKVs.do\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div header=\"名称\" field=\"text\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div header=\"频次编码\" field=\"id\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div header=\"次数\" field=\"execCount\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"orderUsageId\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">用法\r\n");
      out.write("\t\t\t\t\t        \t<div property=\"editor\" class=\"mini-combobox\" popupWidth=\"400\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/medUsage/getKVs.do\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t required=\"true\" allowInput=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div property=\"columns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div header=\"编号\" field=\"id\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div header=\"药品用法\" field=\"text\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"orderExecuteTime\" width=\"150\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\">开嘱日期</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"bookOperName\"  headerAlign=\"center\" align=\"center\">登记人</div>\r\n");
      out.write("\t\t\t\t\t        <div field=\"bookTime\" width=\"150\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\">登记时间</div>\r\n");
      out.write("\t       \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tmini.parse();\r\n");
      out.write("\t\tvar form = new mini.Form(\"form1\");\r\n");
      out.write("\t\tvar grid = mini.get(\"grid1\");\r\n");
      out.write("\t\tvar bookTime = mini.get(\"#bookTime\");\r\n");
      out.write("\t\tvar mixOperTime = mini.get(\"#mixOperTime\");\r\n");
      out.write("\t\tvar injectOperTime = mini.get(\"#injectOperTime\");\r\n");
      out.write("\t\tsetTime();\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /commons/include/form.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /commons/include/form.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/form.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /commons/include/form.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("ctx_rpt");
      // /commons/include/form.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/form.jsp(6,0) '${reportContextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${reportContextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
