/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.2
 * Generated at: 2018-05-14 01:07:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.medical.outpatient;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class triageRecordList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1525761782870L));
    _jspx_dependants.put("/commons/include/html_doctype.html", Long.valueOf(1525761798654L));
    _jspx_dependants.put("/commons/include/get.jsp", Long.valueOf(1525827802831L));
    _jspx_dependants.put("jar:file:/E:/workspace.hisnew/hisbase/WebContent/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>门诊分诊管理</title>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/boot.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/commons/dynamic.jsp\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/plugins/template/jquery.tmpl.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/default/css/web.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("\t\n");
      out.write("<script type=\"text/javascript\">  \n");
      out.write("\tvar currentQueue = \"\";\n");
      out.write("\tvar autoCheck = 0;\n");
      out.write("\tvar autotriageNum = 0;\n");
      out.write("\tvar currentRegister = null;\n");
      out.write("\t\n");
      out.write("\t// 初始加载\n");
      out.write("\tfunction load() { \n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 载入已分诊\n");
      out.write("\tfunction triageList(e) {\n");
      out.write("\t\tgrid1.load({\n");
      out.write("\t\t\tqueueId : e.row.queueId\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tgrid2.load({\n");
      out.write("\t\t\tqueueId : e.row.queueId\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 点击患者节点\n");
      out.write("\tfunction onnodeclick(e) { \n");
      out.write("\t\tif(e.row.id == \"0\") {\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\tcurrentRegister = e.row;\n");
      out.write("\t\tvar info = \"\" + e.row.patientId +\" \"+ e.row.text +\" \"+ e.row.age + \" \"+ e.row.sex;\n");
      out.write("\t\tinfo = info.replace(/[\\[\\]]/g,\" \");\n");
      out.write("\t\t$(\".patientInfo\").text(info);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 取消分诊调用\n");
      out.write("\tfunction cancelTriage() {\n");
      out.write("\t\tvar rows = grid1.getSelecteds();\n");
      out.write("\t\ttop.mini.confirm(\"是否要对选中的\"+ rows.length +\"个患者进行取消分诊!!!\", \"提示\", function(action) {\n");
      out.write("\t\t\tif(action == \"ok\") {\n");
      out.write("\t\t\t\tfor(var i = 0; i < rows.length; i++) {\n");
      out.write("\t\t\t\t\tsureCancel(rows[i]);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 取消分诊\n");
      out.write("\tfunction sureCancel(row) {\n");
      out.write("\t\tif (!row) {\n");
      out.write("\t\t\ttop.mini.showTips({content: \"请选择需要取消的分诊记录!\", state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\treturn ;\n");
      out.write("\t\t}\n");
      out.write("\t\tvar queueList = grid.getList();\n");
      out.write("\t\tif(queueList.length <=0 ) {\n");
      out.write("\t\t\ttop.mini.showTips({content: \"当前护士站没有门诊分诊队列! 请维护!\", state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/cancelTriagePatient.do\";\n");
      out.write("\t\tvar data = {recordId : row.recordId};\n");
      out.write("\t\t$.post(url, data, function(r) {\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"success\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t\tgrid1.load({\n");
      out.write("\t\t\t\t\tqueueId : row.queueId\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\trefresh();\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttop.mini.error(r);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 切换是否自动刷新\n");
      out.write("\tfunction onvaluechanged1(e) {\n");
      out.write("\t\tautoCheck = e.value;\n");
      out.write("\t\tautoRefresh();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 切换是否自动分诊\n");
      out.write("\tfunction onvaluechanged2(e) {\n");
      out.write("\t\tautotriageNum = e.value;\n");
      out.write("\t\tautoTriage();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 自动刷新\n");
      out.write("\tfunction autoRefresh() {  \n");
      out.write("\t  if(autoCheck == 0) {\n");
      out.write("\t\t  return ;  \n");
      out.write("\t  }\n");
      out.write("\t  refresh();\n");
      out.write("\t  setTimeout(autoRefresh, 10000);   \n");
      out.write("\t}  \n");
      out.write("\t\n");
      out.write("\t// 自动分诊\n");
      out.write("\tfunction autoTriage() {  \n");
      out.write("\t  if(autotriageNum == 0) {\n");
      out.write("\t\t  return ;  \n");
      out.write("\t  }\n");
      out.write("\t  automaticTriage(); \n");
      out.write("\t  setTimeout(autoTriage, 10000);   \n");
      out.write("\t}  \n");
      out.write("\t\n");
      out.write("\t// 刷新全部\n");
      out.write("\tfunction refresh() {\n");
      out.write("\t\ttree.load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/unTriagePatient.do\");\n");
      out.write("\t\tgrid.load();\n");
      out.write("\t\ttree1.load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/triageRoom/getRoomAndConsole.do\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 分诊操作 \n");
      out.write("\tfunction triage(e) {\n");
      out.write("\t\tvar data = form.getData();   \n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/save.do\";\n");
      out.write("\t\tvar json = mini.encode(data);\n");
      out.write("\t\t$.post(url, {data : json}, function(r) {\n");
      out.write("\t\t\tif(r == \"ok\") {\n");
      out.write("\t\t\t\twin.hide();\n");
      out.write("\t\t\t\ttop.mini.alert(\"分诊成功！\");\n");
      out.write("\t\t\t\tload();\n");
      out.write("\t\t\t\tloadSee();\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttop.mini.alert(r);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 窗取消\n");
      out.write("\tfunction cancel() {\n");
      out.write("\t\twin.hide();\n");
      out.write("\t\twin1.hide();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 搜索界面\n");
      out.write("\tfunction searchWindow(e) {\n");
      out.write("\t\tif(!isNumber(e.sender.value))return ;\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/findTriagePatients.do\";\n");
      out.write("\t\tvar data = {patientId : e.sender.value};\n");
      out.write("\t\t$.post(url, data, function(r) {\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\n");
      out.write("\t\t\t\tgrid3.load({\n");
      out.write("\t\t\t\t\tpatientId : e.sender.value\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t\twin1.show();\n");
      out.write("\t\t\t\twin1.setTitle(\"检索数据\");\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 叫号\n");
      out.write("\tfunction call(e) {\n");
      out.write("\t\tvar row = grid1.getSelected();\n");
      out.write("\t\tif(!row){\n");
      out.write("\t\t\ttop.mini.showTips({content: \"请选择需要叫号的患者！\", state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageCall/call.do\";\n");
      out.write("\t\tvar data = {recordId : row.recordId};\n");
      out.write("\t\tvar fn = function(r) {\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"success\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttop.mini.error(r);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t};\n");
      out.write("\t\t$.post(url, data, fn);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 点击分诊\n");
      out.write("\tfunction openTriage() {\n");
      out.write("\t\tvar node = tree.getSelected();\n");
      out.write("\t\tvar queueList = grid.getList();\n");
      out.write("\t\tif(queueList.length <= 0) {\n");
      out.write("\t\t\ttop.mini.showTips({content: \"当前护士站没有门诊分诊队列!请维护!\", state: \"success\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\treturn ; \n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif(!node || node.id == \"0\") {\n");
      out.write("\t\t\ttop.mini.showTips({content: \"请选中一个患者\", state: \"warning\", x: \"center\", y: \"center\", timeout: 5000});\n");
      out.write("\t\t}\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/getTriageData.do\";\n");
      out.write("\t\tvar data = {registerId: node.id};\n");
      out.write("\t\t$.post(url, data, function(r) {\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\n");
      out.write("\t\t\t\tform.setData(r.register);\n");
      out.write("\t\t\t\tmini.get(\"#queueId\").select(0);\n");
      out.write("\t\t\t\twin.setTitle(\"患者分诊\");\n");
      out.write("\t\t\t\twin.show();\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"success\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttop.mini.error(r);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 取得焦点\n");
      out.write("\tfunction onfocus(e) {\n");
      out.write("\t\te.sender.load(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/getTriageQueue.do\");\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 检索页面行双击\n");
      out.write("\tfunction onrowdblclick(e) { \n");
      out.write("\t\tvar row = grid3.getSelected();\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/getTriageData.do\";\n");
      out.write("\t\tvar data = {registerId: row.registerId, findWay : true};\n");
      out.write("\t\tvar fn = function(r) {\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\n");
      out.write("\t\t\t\tform.setData(r.register);\n");
      out.write("\t\t\t\tmini.get(\"#queueId\").select(0);\n");
      out.write("\t\t\t\twin.setTitle(\"患者分诊\");\n");
      out.write("\t\t\t\twin.show();\n");
      out.write("\t\t\t\twin1.hide();\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1) {\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttop.mini.error(r);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t$.post(url, data, fn);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t // 分诊\n");
      out.write("\tfunction triagePatient(data) {\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/triagePatient.do\";\n");
      out.write("\t//\ttop.mini.confirm(\"当前选中队列:\"+ data.queueName+\"，是否进行分诊!\", \"提示\", function(action) {\n");
      out.write("\t//\t\tif(action == \"ok\") {\n");
      out.write("\t\t\t\t$.post(url, data, function(r) {\n");
      out.write("\t\t\t\t\tif(parseInt(r.state) == 1) {\n");
      out.write("\t\t\t\t\t\ttop.mini.showTips({content: r.message,  state: \"success\", x: \"center\", y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t\t\t\trefresh();\n");
      out.write("\t\t\t\t\t} else if(parseInt(r.state) == -1) {\n");
      out.write("\t\t\t\t\t\ttop.mini.alert(r.message);\n");
      out.write("\t\t\t\t\t} else if(parseInt(r.state) == 0) {\n");
      out.write("\t\t\t\t\t\ttop.mini.confirm(r.message, \"提示\", function(R) {\n");
      out.write("\t\t\t\t\t\t\tif(action == \"ok\") {\n");
      out.write("\t\t\t\t\t\t\t\tdata.triageFlag = false; \n");
      out.write("\t\t\t\t\t\t\t\ttriagePatient(data);\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t} else if(parseInt(r.state) == 2) {\n");
      out.write("\t\t\t\t\t\tjudge(r);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t//}\n");
      out.write("\t//\t});\n");
      out.write("\t} \n");
      out.write("\t\n");
      out.write("\t// 拖拽分诊(一个患者)\n");
      out.write("\tfunction onbeforedrop(e) {\n");
      out.write("\t\tif(!e.targetNode.queueId) {\n");
      out.write("\t\t\te.cancel = true; \n");
      out.write("\t\t\treturn; \n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tvar data = {\n");
      out.write("\t\t\t\tregisterId : e.dragNode.id,\n");
      out.write("\t\t\t\tqueueId : e.targetNode.queueId,\n");
      out.write("\t\t\t\tqueueName : e.targetNode.queueName\t\t\t\n");
      out.write("\t\t\t};\n");
      out.write("\t\t\ttriagePatient(data);\n");
      out.write("\t\t}\n");
      out.write("\t\te.cancel = true; \n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 分诊弹窗确定分诊(一个患者)\n");
      out.write("\tfunction triage() {\n");
      out.write("\t\tvar formData = form.getData();\n");
      out.write("\t\tvar queue = mini.get(\"queueId\");\n");
      out.write("\t\tvar data = {\n");
      out.write("\t\t\t\tqueueId : queue.value,\n");
      out.write("\t\t\t\tqueueName : queue.text,\n");
      out.write("\t\t\t\tregisterId : formData.registerId\n");
      out.write("\t\t};\n");
      out.write("\t\ttriagePatient(data);\n");
      out.write("\t\twin.hide();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 分诊弹窗交互起始\n");
      out.write("\tfunction judge(data) {\n");
      out.write("\t\tvar regLevel = data.regLevel;\n");
      out.write("\t\tvar queue = data.queue;\n");
      out.write("\t\tvar department = data.department;\n");
      out.write("\t\tvar employee = data.employee;\n");
      out.write("\t\tif((regLevel.expertFlag == 1 && queue.expertFlag == 0)) {\n");
      out.write("\t\t\t top.mini.confirm(\"专家挂号进诊普通队列!\\r\\n是否继续?\", \"提示\", function(r) {\n");
      out.write("\t\t\t\tif(r != \"ok\") {\n");
      out.write("\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tA(data);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t} else if(regLevel.expertFlag == 0 && queue.expertFlag == 1) {\n");
      out.write("\t\t\ttop.mini.alert(\"普通挂号进诊专家队列!\");\n");
      out.write("\t\t\t/* top.mini.confirm(\"普通挂号进诊专家队列!\\r\\n是否继续?\", \"提示\", function(r) {\n");
      out.write("\t\t\t\tif(r != \"ok\") {\n");
      out.write("\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tA(data);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}); */\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tA(data);\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 分诊弹窗交互起始1\n");
      out.write("\tfunction A(data) {\n");
      out.write("\t\tvar regLevel = data.regLevel;\n");
      out.write("\t\tvar queue = data.queue;\n");
      out.write("\t\tif(regLevel.reglevelId != queue.reglvlId) {\n");
      out.write("\t\t\ttop.mini.confirm(\"挂号级别与队列级别不一致!\\r\\n是否继续?\", \"提示\", function(r) {\n");
      out.write("\t\t\t\tif(r != \"ok\") {\n");
      out.write("\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\tB(data);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tB(data);\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 分诊弹窗交互起始2\n");
      out.write("\tfunction B(data) {\n");
      out.write("\t\tvar regLevel = data.regLevel;\n");
      out.write("\t\tvar queue = data.queue;\n");
      out.write("\t\tvar department = data.department;\n");
      out.write("\t\tvar employee = data.employee;\n");
      out.write("\t\tif(employee.employeeId != queue.doctorId) {\n");
      out.write("\t\t\ttop.mini.confirm(\"挂号医生与分诊医生不一致!\\r\\n是否继续?\", \"提示\", function(r) {\n");
      out.write("\t\t\t\tif(r != \"ok\") {\n");
      out.write("\t\t\t\t\treturn;\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tC(data);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}  else {\n");
      out.write("\t\t\tC(data);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 分诊弹窗交互起始2\n");
      out.write("\tfunction C(data){\n");
      out.write("\t\tvar regLevel = data.regLevel;\n");
      out.write("\t\tvar queue = data.queue;\n");
      out.write("\t\tvar department = data.department;\n");
      out.write("\t\tvar employee = data.employee;\n");
      out.write("\t\tif(department.orgId != queue.deptId) {\n");
      out.write("\t\t\ttop.mini.confirm(\"挂号科室与分诊科室不一致!\\r\\n是否继续?\", \"提示\", function(r) {\n");
      out.write("\t\t\t\tif(r != \"ok\") {\n");
      out.write("\t\t\t\t\treturn; \n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\tD(data);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tD(data);\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 分诊弹窗交互起始3\n");
      out.write("\tfunction D (data) {\n");
      out.write("\t\tvar regLevel = data.regLevel;\n");
      out.write("\t\tvar queue = data.queue;\n");
      out.write("\t\tvar department = data.department;\n");
      out.write("\t\tvar employee = data.employee;\n");
      out.write("\t\tvar data = {\n");
      out.write("\t\t\tregisterId : data.registerId,\n");
      out.write("\t\t\tqueueId : data.queueId,\n");
      out.write("\t\t\tqueueName : queue.queueName,\n");
      out.write("\t\t\ttriageFlag : false,\n");
      out.write("\t\t\tjudge : false\n");
      out.write("\t\t};\n");
      out.write("\t\ttriagePatient(data);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tvar currentNum = 0;\n");
      out.write("\n");
      out.write("\t// 自动分诊\n");
      out.write("\tfunction automaticTriage(e) {\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/automaticTriagePatient.do\";\n");
      out.write("\t\t$.post(url, null, function(r) {\n");
      out.write("\t\t\tif(parseInt(r.state) == 1) {\n");
      out.write("\t\t\t\trefresh();\n");
      out.write("\t\t\t} else if(parseInt(r.state) == -1){\n");
      out.write("\t\t\t\ttop.mini.showTips({content: r.message, state: \"warning\", x: \"center\",  y: \"center\", timeout: 5000});\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttop.mini.error(r);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t} \n");
      out.write("\t\n");
      out.write("\t// 根据对象分诊\n");
      out.write("\tfunction triagedHelp(queue, patient) {\n");
      out.write("\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/save.do\";\n");
      out.write("\t\tvar fn = function(r) {\n");
      out.write("\t\t\tif(r == \"ok\") {\n");
      out.write("\t\t\t\tload();\n");
      out.write("\t\t\t\tloadSee();\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\ttop.mini.alert(r);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\tvar data = {\n");
      out.write("\t \t\tregisterId : patient.registerId, \n");
      out.write("\t \t\tdoctorId : queue.doctorId, \n");
      out.write("\t \t\tnoonCode : queue.noonId,\n");
      out.write("\t \t\tpatientId : patient.patientId,\n");
      out.write("\t \t\tpatientName : patient.patientName,\n");
      out.write("\t \t\tregisterTime : patient.registerTime,\n");
      out.write("\t \t\tregisterDeptId : patient.registerDeptId, \n");
      out.write("\t \t\tqueueId : queue.queueId,\n");
      out.write("\t \t\troomId : queue.roomId,\n");
      out.write("\t \t\tconsoleId : queue.consoleId\n");
      out.write("\t\t};\n");
      out.write("\t\tvar json = mini.encode(data);\n");
      out.write("\t\t$.post(url, {data : json}, fn);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 上屏\n");
      out.write("\tfunction videoPlay() {\n");
      out.write("\t\twindow.open ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/video.do', '分诊显屏', 'height=500, width=900, top=0, left=0, toolbar=no, menubar=no, scrollbars=no, resizable=no,location=no, status=no')\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t// 渲染表格\n");
      out.write("\tfunction ondrawcell(e) {\n");
      out.write("\t\tif (e.column.field == \"doctorId\") {\n");
      out.write("\t\t\t\te.cellStyle = \"color:#000;font-size:13px;font-weight:bold;\";\n");
      out.write("\t\t}\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t// 退出\n");
      out.write("\tfunction exit() {\n");
      out.write("\t\tvar currentTab = top.tabs.activeIndex;\n");
      out.write("\t\tvar tabs = top.tabs;\n");
      out.write("\t\ttabs.removeTab(currentTab);\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction show() {\n");
      out.write("\t\t$(\".toolbar, .splitter\").show();\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\ttop.on(\"EVENT_ORG_CHANGED\", refresh);\n");
      out.write("\t$(window).unload(function() {\n");
      out.write("\t\ttop.un(\"EVENT_ORG_CHANGED\", refresh);\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div class=\"mini-toolbar toolbar\" style=\"display:none;\">\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-refresh\" onclick=\"refresh\">刷新</a>\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-minus-circle\" onclick=\"openTriage\">分诊</a>\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-window-close\" onclick=\"cancelTriage\">取消分诊</a>\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-expand\" onclick=\"automaticTriage\">自动分诊</a>\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-bullhorn\" onclick=\"call\">叫号</a>\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-television\" onclick=\"videoPlay\">上屏</a>\n");
      out.write("\t\t<a class=\"mini-button\" iconCls=\"fa fa-window-close\" onclick=\"exit\">退出</a>\n");
      out.write("\t\t<div style=\"float:right;padding:0 20px 0 0;\">\n");
      out.write("\t\t\t<a class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged1\" trueValue=\"1\" falseValue=\"0\">自动刷新</a>\n");
      out.write("\t\t\t<a class=\"mini-checkbox\">外屏</a>\n");
      out.write("\t\t\t<a class=\"mini-checkbox\" onvaluechanged=\"onvaluechanged2\" trueValue=\"1\" falseValue=\"0\">自动分诊</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"mini-fit\">\n");
      out.write("\t\t<div class=\"mini-splitter splitter\" style=\"width: 100%;height:100%;display:none;\" handlerSize=\"6\" allowResize=\"false\">\n");
      out.write("\t\t\t<div size=\"20%\" showCollapseButton=\"false\">\n");
      out.write("\t\t\t\t<h3 style=\"\">\n");
      out.write("\t\t\t\t\t患者查询： <input class=\"mini-textbox\" id=\"searchKey\" onenter=\"searchWindow\" emptyText=\"根据患者唯一号查询\"/>\n");
      out.write("\t\t\t\t</h3>\n");
      out.write("\t\t\t\t<div id=\"tabs\" class=\"mini-tabs\">\n");
      out.write("\t\t\t\t\t<div class=\"mini-fit\" title=\"分诊列表\">\n");
      out.write("\t\t\t\t\t\t<ul id=\"tree1\" class=\"mini-tree\" resultAsTree=\"false\" expandOnLoad=\"true\" onnodeclick=\"onnodeclick\" \n");
      out.write("\t\t\t\t\t\t\tmultiSelect=\"true\" allowDrag=\"true\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/unTriagePatient.do\">\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"mini-fit\" title=\"已看诊列表\">\n");
      out.write("\t\t\t\t\t\t<h3>\n");
      out.write("\t\t\t\t\t\t\t日期 : <input id=\"date1\" class=\"mini-datepicker\"/><a class=\"mini-button\" iconCls=\"icon-search\">查询</a>\n");
      out.write("\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div showCollapseButton=\"false\">\n");
      out.write("\t\t\t\t<div class=\"mini-splitter\" style=\"width:100%; height:100%;\" handlerSize=\"6\">\n");
      out.write("\t\t\t\t\t\t<div size=\"75%\" showCollapseButton=\"false\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"mini-splitter\" vertical=\"true\" style=\"width:100%;height:100%;\" handlerSize=\"6\">\n");
      out.write("\t\t\t\t\t\t\t\t<div size=\"40%;\" showCollapseButton=\"false\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"patientInfo\">患者信息</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t队列信息\n");
      out.write("\t\t\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"mini-fit\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div id=\"grid1\" class=\"mini-treegrid\" style=\"width:100%; height:100%;\" showPager=\"false\" ondrawcell=\"ondrawcell\" onrowClick=\"triageList\" allowRowSelect=\"true\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tallowDrop=\"true\" onbeforedrop=\"onbeforedrop\"  url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/getTriageQueue.do\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div property=\"columns\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div type=\"indexcolumn\">序号</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div field=\"tag.showQueueName\" headerAlign=\"center\" align=\"center\" width=\"320\">队列名称</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"deptId\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\" width=\"200\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t科室<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do\"/>\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div field=\"doctorId\" headerAlign=\"center\" align=\"center\">医生编号</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"doctorId\" headerAlign=\"center\" type=\"comboboxColumn\" align=\"center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t医生<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do\"/>\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"reglvlId\" type=\"comboboxColumn\" headerAlign=\"center\" align=\"center\">级别\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\"  url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/expense/maintenance/register/regLevel/getKVs.do\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"roomId\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t诊室<input property=\"editor\" class=\"mini-combobox\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t  url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/triageRoom/getKVs.do\"/>\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"consoleId\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t诊台<input property=\"editor\" class=\"mini-combobox\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t  url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/triageConsole/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"tag.triageNum\" headerAlign=\"center\" align=\"center\" visible=\"true\">候诊人数</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"noonId\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t午别<input property=\"editor\" class=\"mini-combobox\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t   \t  url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/basedata/datamanager/noon/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div size=\"40%;\" showCollapseButton=\"false\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"tab1\" class=\"mini-tabs\" style=\"width:100%;height:100%;border:0px;margin:5px 0 0 0;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mini-fit\" title=\"已分诊列表\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"grid2\" class=\"mini-datagrid\" style=\"width:100%;height:100%;\" showPager=\"false\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/getTriagePatient.do\" multiSelect=\"true\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div property=\"columns\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div type=\"checkColumn\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div type=\"indexcolumn\" headerAlign=\"center\" align=\"center\" width=\"50\">序号</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"patientId\" headerAlign=\"center\" align=\"center\">病人ID</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"patientName\" headerAlign=\"center\" align=\"center\">姓名</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"sexCode\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">性别\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" data=\"[{id : 1, text :'男'},{id : 2, text :'女'}]\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"age\" headerAlign=\"center\" align=\"center\">年龄</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"deptId\" headerAlign=\"center\" align=\"center\"  type=\"comboboxColumn\" width=\"180\">挂号科室\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"registerDoctId\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">挂号医生\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"doctorId\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">看诊医生\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"triageTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\" width=\"150\">分诊时间</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div field=\"seeSerialId\" headerAlign=\"center\" align=\"center\">分诊序号</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"registerTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\" width=\"150\">预约看诊时间</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div field=\"tag.totCost\" headerAlign=\"center\" align=\"center\">金额</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"mini-fit\" title=\"已看诊列表\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div id=\"grid3\" class=\"mini-datagrid\" style=\"width:100%;height:100%;\" showPager=\"false\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/triageRecord/getSeePatient.do\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div property=\"columns\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div type=\"indexcolumn\">序号</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"patientId\" headerAlign=\"center\" align=\"center\"> 病人ID</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"patientName\" headerAlign=\"center\" align=\"center\"> 姓名</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"sexCode\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\"> 性别\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" data=\"[{id : 1, text :'男'},{id : 2, text :'女'}]\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"age\" headerAlign=\"center\" align=\"center\">年龄</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"deptId\" headerAlign=\"center\" align=\"center\"  type=\"comboboxColumn\" width=\"180\">挂号科室\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"registerDoctId\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">挂号医生\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"doctorId\" headerAlign=\"center\" align=\"center\" type=\"comboboxColumn\">看诊医生\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"triageTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\" width=\"180\">分诊时间</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- <div field=\"seeSerialId\" headerAlign=\"center\" align=\"center\">分诊序号</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"seeTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\" width=\"180\">预约看诊时间</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div field=\"tag.totCost\" headerAlign=\"center\" align=\"center\">金额</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div showCollapseButton=\"false\">\n");
      out.write("\t\t\t\t\t\t\t<ul id=\"tree2\" class=\"mini-tree\" resultAsTree=\"false\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/common/triageRoom/getRoomAndConsole.do\" expandOnLoad=\"true\">\n");
      out.write("\t\t\t\t\t\t\t</ul>\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- 分诊信息 -->\n");
      out.write("\t<div id=\"win1\" class=\"mini-window\" style=\"width:250px;text-align:center;height:250px; display:none;\">\n");
      out.write("\t \t<div id=\"form1\">\n");
      out.write("\t \t\t<input class=\"mini-hidden\" name=\"registerId\"/>\n");
      out.write("\t\t \t<table id=\"win1_table\">\n");
      out.write("\t\t \t\t<tr><td class=\"blue\">病历号:</td><td> <input class=\"mini-textbox\" name=\"patientId\" readOnly=\"true\" enabled=\"false\" width=\"180\"/></td></tr>\n");
      out.write("\t\t \t\t<tr><td class=\"blue\">患者姓名:</td><td> <input class=\"mini-textbox\" name=\"patientName\" readOnly=\"true\" enabled=\"false\" width=\"180\"/></td></tr>\n");
      out.write("\t\t \t\t<tr><td class=\"blue\">挂号日期:</td><td class=\" noIcon\"> <input class=\"mini-datePicker\" name=\"registerTime\" dateFormat=\"yyyy-MM-dd HH:mm:ss\" readOnly=\"true\" enabled=\"false\" width=\"180\"/></td></tr>\n");
      out.write("\t\t \t\t<tr><td class=\"blue\">挂号科室:</td><td class=\" noIcon\"> <input class=\"mini-combobox\" name=\"registerDeptId\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do\" readOnly=\"true\" enabled=\"false\" width=\"180\"/></td></tr>\n");
      out.write("\t\t \t\t<tr>\n");
      out.write("\t\t \t\t\t<td class=\"blue\">分诊队列: </td>\n");
      out.write("\t\t \t\t\t<td>\n");
      out.write("\t\t \t\t\t\t<input class=\"mini-combobox\" name=\"queueId\" valueField=\"queueId\" onfocus=\"onfocus\" textField=\"tag.showQueueName\" id=\"queueId\"\n");
      out.write("\t\t \t\t\t\t\t  width=\"180\" popupwidth=\"280\"/>\n");
      out.write("\t\t \t\t\t</td>\n");
      out.write("\t\t \t\t</tr>\n");
      out.write("\t\t \t\t\n");
      out.write("\t\t \t\t<tr>\n");
      out.write("\t\t \t\t\t<td colspan=\"2\">\n");
      out.write("\t\t \t\t\t\t<a class=\"mini-button\" iconCls=\"fa fa-check\" onclick=\"triage\">确定</a>\n");
      out.write("\t\t \t\t\t\t　　　　\n");
      out.write("\t\t \t\t\t\t<a class=\"mini-button\" iconCls=\"fa fa-window-close\" onclick=\"cancel\">取消</a>\n");
      out.write("\t\t \t\t\t</td>\n");
      out.write("\t\t \t\t</tr>\n");
      out.write("\t\t \t</table>\n");
      out.write("\t \t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<!-- 检索患者 -->\n");
      out.write("\t<div id=\"win2\" class=\"mini-window\" style=\"width:900px;height:300px;display:none;\">\n");
      out.write("\t\t<div class=\"mini-fit\">\n");
      out.write("\t\t\t<div id=\"grid4\" class=\"mini-datagrid\" borderStyle=\"border:1px solid #ccc; border-right:0;border-bottom:0px solid #ccc;\" showPager=\"false\" allowRowSelect=\"true\"\n");
      out.write("\t\t\t\t multiSelect=\"true\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/medical/outpatient/opExpRegister/findTriagePatients.do\">\n");
      out.write("\t\t\t\t<div property=\"columns\">\n");
      out.write("\t\t\t\t\t<div type=\"indexcolumn\">序号</div>\n");
      out.write("\t\t\t\t\t<div field=\"registerTime\" headerAlign=\"center\" align=\"center\" dateFormat=\"yyyy-MM-dd HH:mm:ss\">挂号时间 </div>\n");
      out.write("\t\t\t\t\t<div field=\"patientName\" headerAlign=\"center\" align=\"center\">姓名</div>\n");
      out.write("\t\t\t\t\t<div field=\"tag.state\" headerAlign=\"center\" align=\"center\" >状态</div>\n");
      out.write("\t\t\t\t\t<div field=\"registerDeptId\" headerAlign=\"center\" align=\"center\"  type=\"comboboxColumn\">挂号科室\n");
      out.write("\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysOrg/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div field=\"registerDoctId\" headerAlign=\"center\" align=\"center\"  type=\"comboboxColumn\">挂号医生\n");
      out.write("\t\t\t\t\t\t<input property=\"editor\" class=\"mini-combobox\" url=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/platform/system/sysUser/getKVs.do\"/>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div field=\"patientId\" headerAlign=\"center\" align=\"center\">编码 </div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div style=\"float:right;text-align:right;height:50px; line-height:50px; width:100%;border-top:1px solid #ccc;\">\n");
      out.write("\t\t\t<a class=\"mini-button\" onclick=\"onrowdblclick\" iconCls=\"fa fa-check\">确定</a>　　　\n");
      out.write("\t\t\t<a class=\"mini-button\" onclick=\"cancel\" iconCls=\"fa fa-window-close\">取消</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tmini.parse();\n");
      out.write("\tvar tree = mini.get(\"tree1\");\n");
      out.write("\tvar tree1 = mini.get(\"tree2\");\n");
      out.write("\tvar win = mini.get(\"win1\");\n");
      out.write("\tvar win1 = mini.get(\"win2\");\n");
      out.write("\tvar grid = mini.get(\"grid1\");\n");
      out.write("\tvar grid1 = mini.get(\"grid2\");\n");
      out.write("\tvar grid2 = mini.get(\"grid3\");\n");
      out.write("\tvar grid3 = mini.get(\"grid4\");\n");
      out.write("\tvar tab = mini.get(\"tab1\");\n");
      out.write("\tvar form = new mini.Form(\"#form1\");\n");
      out.write("\t// autoRefresh();\n");
      out.write("\tload();\n");
      out.write("\tshow();\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /commons/include/get.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /commons/include/get.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/get.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /commons/include/get.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("emr");
      // /commons/include/get.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/commons/include/get.jsp(6,0) '${emrContextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${emrContextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
